### ISSUE TITLE
(GDAX) Order gets filled at lower price than expected 

### ISSUE THREAD

**Issue by abmbc** [askmike/gekko#2372] opened 2018-07-27 10:25 UTC
![console](https://user-images.githubusercontent.com/41784698/43315711-bf183656-918e-11e8-8ba4-79550eff7f35.png)

My strategy advised an order for 71.95, it was placed but then within minutes cancelled and a new order was placed at 71.90 which was filled:

![filledorder](https://user-images.githubusercontent.com/41784698/43315808-11f03a4a-918f-11e8-8c85-0dcfe4ef8191.png)

problem is that my strategy now thinks the order was filled at 71.95 not 71.90, is there any way gekko could check when an order is filled and relay that info to the strategy?

**Comment by askmike** [comment] 2018-07-27 13:29
So within Gekko the alpha (your strategy) and the execution (gekko broker's sticky order) are separated and information between them is minimal.

> is there any way gekko could check when an order is filled and relay that info to the strategy?

Yes there is an experimental way (which might change after advanced orders like stoplosses), implemented in #1810:

You can add a function called `processTrade` to your strategy which will be passed a `tradeCompleted` event, see here: https://gekko.wizb.it/docs/internals/events.html#tradeCompleted-event

Unfortunately if Gekko Broker decides not to trade for whatever reason (either [this one](https://github.com/askmike/gekko/blob/develop/plugins/trader/trader.js#L165-L175) or [this one](https://github.com/askmike/gekko/blob/develop/exchange/exchangeUtils.js#L60-L87)) you won't see a notification. So better not to rely on it for now.

-----

Closing this as it's not a bug (this is the bug tracker), but feel free to keep commenting.

**Closed as completed by askmike** 2018-07-27 13:29 UTC
