### ISSUE TITLE
Installation problem: (Node: 12) UnhandledPromisedRejectionWarning

### ISSUE THREAD

**Issue by nhuongle** [askmike/gekko#1432] opened 2017-12-07 08:49 UTC
Windows 10
![image](https://user-images.githubusercontent.com/34335021/33706242-b917a7e6-daf0-11e7-88f2-5bfdc35569f3.png)
![image](https://user-images.githubusercontent.com/34335021/33706253-c37c9660-daf0-11e7-94cc-1d6c9c18bc78.png)

I was able to open http://localhost:3000/, however, none of the function is working for me. Anyone has any suggestion on how to fix these problems? Thank you.

**Comment by cmroche** [comment] 2017-12-08 00:29
Duplicate of #1393, #1375 , #1373 

Try syncing and using the develop branch please.

The warning about the unhandled promise is not related.

**Comment by askmike** [comment] 2017-12-08 05:02
If the problem persists after trying out the things above, please comment here :)

**Closed as completed by askmike** 2017-12-08 05:02 UTC
