### ISSUE TITLE
[Feature Request] Tulip Indikators.

### ISSUE THREAD

**Issue by decoye** [askmike/gekko#1032] opened 2017-08-23 15:45 UTC
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**

[*] feature request

I like tulip indicators over the talib because the documentation is available and its well documented. would it not be nice to have this also available?

All the best.

**Comment by askmike** [comment] 2017-08-23 16:37
It would be yes! However it's a lot of work to add. Closing this as a duplicate of #708.

**Closed as completed by askmike** 2017-08-23 16:37 UTC

**Comment by decoye** [comment] 2017-08-23 16:54
alright thanks tho.

Am 23.08.17 um 18:37 schrieb Mike van Rossum:
