### ISSUE TITLE
Even though Gekko has enough history data, it only starts trading after waiting for historySize

### ISSUE THREAD

**Issue by pelletencate** [askmike/gekko#964] opened 2017-08-14 09:20 UTC
### Steps to reproduce:

1. Set up Gekko to download the necessary history data before trading by setting historySize in config.js. (See below for patch).
2. Start Gekko using the command line.

### Expected behavior:

Gekko uses the downloaded data in history to start trading immediately

### Actual behavior

Even though Gekko downloaded the data, it still waited for historySize after firing it up before it did its first trade. 

My historySize is a little bit over 2 days. Because of this, I miss several profitable trades, and – more importantly – every time I restart it, Gekko won't trade for another 2 days.

In order to get more than 4 hours of history data, I had to apply the following patch:

```
diff --git a/core/tools/dataStitcher.js b/core/tools/dataStitcher.js
index da3cb5d..d1bfe2b 100644
--- a/core/tools/dataStitcher.js
+++ b/core/tools/dataStitcher.js
@@ -87,7 +87,7 @@ Stitcher.prototype.prepareHistoricalData = function(done) {

     // Limit the history Gekko can try to get from the exchange.
     var minutesAgo = endTime.diff(idealExchangeStartTime, 'minutes');
-    var maxMinutesAgo = 4 * 60; // 4 hours
+    var maxMinutesAgo = 7 * 24 * 60; // Limit pre-fetched history to 1 week
     if(minutesAgo > maxMinutesAgo) {
       log.info('\tPreventing Gekko from requesting', minutesAgo, 'minutes of history.');
       idealExchangeStartTime = endTime.clone().subtract('minutes', maxMinutesAgo);
```

**Comment by askmike** [comment] 2017-08-14 10:24
Your proposed diff doesn't change the behaviour of loading stored data into Gekko, just how "old" the initial fetch can be (with the idea that if this is long enough, you don't need locally stored data).

The reason for `maxMinutesAgo` is a performance reason, see here: https://gekko.wizb.it/docs/extending/add_an_exchange.html#getTrades

If Gekko fetches two much data at once things will break, for that reason the importer was designed to break up a lot of data into multiple fetches.

-----

As for your bug: If your strat requires 2 days of data:

Gekko needs to feed your strat with 2 days of data, it will try to load local data from disk and combine it with data from the exchange (limited by what I described above). If you turn on debug on the config (in CLI mode) you will see debug logging about why in your case Gekko was unable to combine the data.

**Comment by GuyPaddock** [comment] 2017-08-15 22:02
I'm seeing the same thing.

According to the UI, I have about 3 days worth of data. But, when I configure and run CLI (based on the same data set), I see this for GDAX:
```
2017-08-15 17:58:25 (DEBUG):            Available local data:
2017-08-15 17:58:25 (DEBUG):                    from: 20 minutes ago
2017-08-15 17:58:25 (DEBUG):                    to: 8 minutes ago
2017-08-15 17:58:25 (INFO):             Usable local data available, trying to match with exchange data..
2017-08-15 17:58:25 (DEBUG):            Fetching exchange data since 23 minutes ago
2017-08-15 17:58:25 (DEBUG):    Scanning back in the history needed...
2017-08-15 17:58:25 (DEBUG):    2017-08-15T21:35:00+00:00
2017-08-15 17:58:27 (DEBUG):    Scanning backwards...2017-08-15T21:57:45.33Z
2017-08-15 17:58:27 (DEBUG):    Scanning backwards...2017-08-15T21:56:02.139Z
2017-08-15 17:58:27 (DEBUG):    Scanning backwards...2017-08-15T21:52:43.072Z
2017-08-15 17:58:27 (DEBUG):    Scanning backwards...2017-08-15T21:43:08.251Z
2017-08-15 17:58:27 (DEBUG):    Backwards: 2017-08-15T21:33:10.816Z (19345832) to 2017-08-15T21:34:44.862Z (19345931)
2017-08-15 17:58:27 (DEBUG):    Backwards: 2017-08-15T21:34:46.887Z (19345932) to 2017-08-15T21:38:55.322Z (19346031)
2017-08-15 17:58:27 (DEBUG):    Backwards: 2017-08-15T21:38:55.322Z (19346032) to 2017-08-15T21:41:49.02Z (19346131)
2017-08-15 17:58:28 (DEBUG):    Backwards: 2017-08-15T21:41:51.966Z (19346132) to 2017-08-15T21:43:08.251Z (19346231)
2017-08-15 17:58:29 (DEBUG):    Backwards: 2017-08-15T21:43:08.251Z (19346232) to 2017-08-15T21:47:01.812Z (19346331)
2017-08-15 17:58:34 (DEBUG):    Backwards: 2017-08-15T21:47:10.947Z (19346332) to 2017-08-15T21:50:24.038Z (19346431)
2017-08-15 17:58:34 (DEBUG):    Backwards: 2017-08-15T21:50:24.038Z (19346432) to 2017-08-15T21:52:43.072Z (19346531)
2017-08-15 17:58:34 (DEBUG):    Backwards: 2017-08-15T21:52:43.072Z (19346532) to 2017-08-15T21:53:54.971Z (19346631)
2017-08-15 17:58:34 (DEBUG):    Backwards: 2017-08-15T21:53:54.971Z (19346632) to 2017-08-15T21:56:00.699Z (19346731)
2017-08-15 17:58:35 (DEBUG):    Backwards: 2017-08-15T21:56:02.139Z (19346732) to 2017-08-15T21:57:45.33Z (19346831)
2017-08-15 17:58:35 (DEBUG):    Backwards: 2017-08-15T21:57:45.33Z (19346832) to 2017-08-15T21:58:25.755Z (19346931)
2017-08-15 17:58:35 (DEBUG):    Backwards: 2017-08-15T21:57:46.591Z (19346841) to 2017-08-15T21:58:33.151Z (19346940)
2017-08-15 17:58:35 (DEBUG):    Backwards: 2017-08-15T21:57:46.591Z (19346841) to 2017-08-15T21:58:33.151Z (19346940)
2017-08-15 17:58:35 (DEBUG):    Scan finished: data found:1300
2017-08-15 17:58:35 (DEBUG):            Available exchange data:
2017-08-15 17:58:35 (DEBUG):                    from: 25 minutes ago
2017-08-15 17:58:35 (DEBUG):                    to: 0 minutes ago
2017-08-15 17:58:35 (DEBUG):            Exchange offered more data than locally available. Ignoring local data
2017-08-15 17:58:35 (DEBUG):            Unable to stitch datasets.
2017-08-15 17:58:35 (INFO):             Not seeding locally available data to the trading method.
2017-08-15 17:58:35 (INFO):             However the exchange returned enough data anyway!
```

**Comment by GuyPaddock** [comment] 2017-08-15 22:21
Also, according to this, running through the UI cannot use stitched data? https://github.com/askmike/gekko/issues/943#issuecomment-321793389

**Comment by GuyPaddock** [comment] 2017-08-15 23:47
After clearing out my history and re-running, I am seeing behavior that suggests the OP is correct that there is a bug that's limiting the ability to use local data to no more than 240 minutes.

```
2017-08-15 19:36:07 (INFO):             The trading method requests 1008 minutes of historic data. Checking availablity..
2017-08-15 19:36:07 (INFO):

2017-08-15 19:36:07 (INFO):             No usable local data available, trying to get as much as possible from the exchange..
2017-08-15 19:36:07 (INFO):             Preventing Gekko from requesting 1008 minutes of history.
2017-08-15 19:36:07 (DEBUG):            Fetching exchange data since 240 minutes ago
2017-08-15 19:36:07 (DEBUG):    Scanning back in the history needed...
2017-08-15 19:36:07 (DEBUG):    2017-08-15T19:36:00+00:00
2017-08-15 19:36:07 (DEBUG):    Scanning backwards...2017-08-15T23:33:31.077Z
2017-08-15 19:36:08 (DEBUG):    Scanning backwards...2017-08-15T23:32:27.932Z
2017-08-15 19:36:08 (DEBUG):    Scanning backwards...2017-08-15T23:24:23.529Z
2017-08-15 19:36:08 (DEBUG):    Scanning backwards...2017-08-15T23:14:37.333Z
2017-08-15 19:36:14 (DEBUG):    Scanning backwards...2017-08-15T23:03:41.645Z
2017-08-15 19:36:15 (DEBUG):    Scanning backwards...2017-08-15T22:53:06.763Z
2017-08-15 19:36:15 (DEBUG):    Scanning backwards...2017-08-15T22:44:58.693Z
2017-08-15 19:36:15 (DEBUG):    Scanning backwards...2017-08-15T22:33:01.931Z
2017-08-15 19:36:15 (DEBUG):    Scanning backwards...2017-08-15T22:11:52.947Z
2017-08-15 19:36:15 (DEBUG):    Scanning backwards...2017-08-15T21:58:13.761Z
2017-08-15 19:36:16 (DEBUG):    Scanning backwards...2017-08-15T21:33:44.29Z
2017-08-15 19:36:16 (DEBUG):    Scanning backwards...2017-08-15T21:08:42.839Z
2017-08-15 19:36:16 (DEBUG):    Scanning backwards...2017-08-15T20:32:22.492Z
2017-08-15 19:36:16 (DEBUG):    Scanning backwards...2017-08-15T20:07:59.199Z
2017-08-15 19:36:17 (DEBUG):    Backwards: 2017-08-15T19:26:11.721Z (19340878) to 2017-08-15T19:29:11.407Z (19340977)
```

**Comment by askmike** [comment] 2017-08-16 08:56
@GuyPaddock OP has an issue that his Gekko has enough data ("Even though Gekko has enough history data"), if you clear your history it's not the same situation.

Gekko limits fetching in one go, if you need more data you should import first. See here: https://gekko.wizb.it/docs/extending/add_an_exchange.html#getTrades

**Comment by GuyPaddock** [comment] 2017-08-16 13:47
@askmike I agree with the assessment that the two are different (using history vs. cleaning history); I realized after my last comment in this issue that if you want more than 240 minutes of data, you have to run import first.

In addition, as you mentioned in #975, because I was able to use data I had imported (18 hours worth) on subsequent runs, that shows that I was not experiencing the OPs issue.

**One last question though:** in my earlier comment (https://github.com/askmike/gekko/issues/964#issuecomment-322602285), I was getting the error "Unable to stitch datasets." after trying to use data that was originally imported via the UI. What would cause that error?

**Comment by askmike** [comment] 2017-08-16 14:09
That was in the line above:

> Exchange offered more data than locally available. Ignoring local data

The only local data was:

> 2017-08-15 17:58:25 (DEBUG):                    from: 20 minutes ago
> 2017-08-15 17:58:25 (DEBUG):                    to: 8 minutes ago

But the exchange returned:

> 2017-08-15 17:58:35 (DEBUG):                    from: 25 minutes ago
> 2017-08-15 17:58:35 (DEBUG):                    to: 0 minutes ago

So stitching doesn't make sense.

**Comment by GuyPaddock** [comment] 2017-08-16 14:57
Hmm, ok. The odd part was that I had just completed an import via the UI that loaded in August 1, 2017 through August 15, 2017, before switching to CLI. Do the two store data in separate parts of SQLite?

**Comment by askmike** [comment] 2017-08-16 15:24
No, Gekko only uses 1 minute candles stored inside a single table. When you run a gekko that needs some data an analysis is done that figures out if the candles are minutes apart (there is no point stitching data from a month old to exchange data from 1 hour ago).

I am closing this as it's going off topic (but feel free to ask questions). @pelletencate if you can provide logs for your initial issue please let me know!

**Closed as completed by askmike** 2017-08-16 15:24 UTC
Labels: cannot-reproduce

**Comment by dreammaker** [comment] 2018-04-12 21:51
I'm running into this problem.  I believe the way to reproduce it is to not have any recent local data.  (I'm setting candleSize to 1 and historySize to 10 to make sure I'm not running into the max that you referred to.)

I'm reading through `dataStitcher.js`.  I see that in `seedLocalData()` it uses candles from local data and passes them to the batcher.  However, where is the exchange data ever used?  In `checkExchangeTrades()`, it seems like the resulting trades from the exchange are discarded.  Only the from and to dates are passed to the callback.  What am I missing here?  Does `getTrades()` have some magic in it that propagates the trades?

Here is my CLI output.  Strategy's `check()` isn't getting called for a long time.

    2018-04-12 17:13:18 (INFO):	Setting up Gekko in realtime mode
    2018-04-12 17:13:18 (INFO):
    2018-04-12 17:13:18 (INFO):	Setting up:
    2018-04-12 17:13:18 (INFO):		 Trading Advisor
    2018-04-12 17:13:18 (INFO):		 Calculate trading advice
    2018-04-12 17:13:18 (INFO):		 Using the strategy: MACD
    2018-04-12 17:13:18 (WARN):	TALIB indicators could not be loaded, they will be unavailable.
    2018-04-12 17:13:18 (WARN):	TULIP indicators could not be loaded, they will be unavailable.
    2018-04-12 17:13:19 (INFO):		The trading method requests 10 minutes of historic data. Checking availablity..
    2018-04-12 17:13:19 (INFO):

    2018-04-12 17:13:19 (INFO):		No usable local data available, trying to get as much as possible from the exchange..
    2018-04-12 17:13:19 (DEBUG):		Fetching exchange data since 10 minutes ago
    2018-04-12 17:13:19 (DEBUG):	Scanning back in the history needed...
    2018-04-12 17:13:19 (DEBUG):	2018-04-12T21:03:00Z
    2018-04-12 17:13:19 (DEBUG):	Scanning backwards...2018-04-12T21:09:25.402Z
    2018-04-12 17:13:19 (DEBUG):	Scanning backwards...2018-04-12T21:03:26.859Z
    2018-04-12 17:13:20 (DEBUG):	Backwards: 2018-04-12T20:58:10.082Z (41498351) to 2018-04-12T20:59:25.664Z (41498450)
    2018-04-12 17:13:20 (DEBUG):	Backwards: 2018-04-12T20:59:25.664Z (41498451) to 2018-04-12T20:59:46.191Z (41498550)
    2018-04-12 17:13:21 (DEBUG):	Backwards: 2018-04-12T20:59:46.191Z (41498551) to 2018-04-12T21:03:26.859Z (41498650)
    2018-04-12 17:13:21 (DEBUG):	Backwards: 2018-04-12T21:03:26.859Z (41498651) to 2018-04-12T21:06:48.829Z (41498750)
    2018-04-12 17:13:22 (DEBUG):	Backwards: 2018-04-12T21:06:49.589Z (41498751) to 2018-04-12T21:09:25.402Z (41498850)
    2018-04-12 17:13:22 (DEBUG):	Backwards: 2018-04-12T21:09:25.402Z (41498851) to 2018-04-12T21:13:17.061Z (41498950)
    2018-04-12 17:13:23 (DEBUG):	Backwards: 2018-04-12T21:09:25.402Z (41498851) to 2018-04-12T21:13:17.061Z (41498950)
    2018-04-12 17:13:23 (DEBUG):	Scan finished: data found:700
    2018-04-12 17:13:23 (DEBUG):		Available exchange data:
    2018-04-12 17:13:23 (DEBUG):			from: 15 minutes ago
    2018-04-12 17:13:23 (DEBUG):			to: 0 minutes ago
    2018-04-12 17:13:23 (DEBUG):		Unable to stitch datasets.
    2018-04-12 17:13:23 (INFO):		Not seeding locally available data to the trading method.
    2018-04-12 17:13:23 (INFO):		However the exchange returned enough data anyway!
    2018-04-12 17:13:23 (INFO):	Starting to watch the market: GDAX BTC/USD
    2018-04-12 17:13:23 (DEBUG):	scheduling ticks
    2018-04-12 17:13:23 (DEBUG):	Requested BTC/USD trade data from GDAX ...
    2018-04-12 17:13:23 (DEBUG):	Processing 100 new trades. From 2018-04-12 21:09:25 UTC to 2018-04-12 21:13:17 UTC. (4 minutes)

**Comment by dreammaker** [comment] 2018-04-12 22:15
See also: #1689

**Comment by paja72** [comment] 2019-09-29 14:56
Hello @askmike,
I read this thread.. but I did't find solution for this..
I found that UI TradingBot is unable to use the imported history (freshly imported data), while CLI can handle it.
Is that the intention?
It would be nice if UI bot could do that and one can see results of trades in pretty form.
However, I must say that Gekko is a nice piece of software.
Ingenious. :)
Paul
