### ISSUE TITLE
Gekko web ui - giving wrong trades

### ISSUE THREAD

**Issue by krunalbarot** [askmike/gekko#1004] opened 2017-08-19 08:53 UTC
hi all,

I have been running gekko web ui since last 2 days. Have setup history and stuff..

the first trade it did a short  - and then buy but it showing as negative in the roundtrips..

any way to see the logs for when the trade is made ? 
also is there an option to enable logs for the UI mode? 

thanks

**Comment by askmike** [comment] 2017-08-19 11:04
> any way to see the logs for when the trade is made ?

Not yet, but a feature is being discussed in #978.

> also is there an option to enable logs for the UI mode?

See this discussion: #972.

----

As for your issue "Gekko web ui - giving wrong trades" what is exactly wrong about them?

**Comment by krunalbarot** [comment] 2017-08-19 12:39
the wrong thing is like - it sells when it should buy and vice versa .. it looks like that ..
so what i will do is enable the logs in UI mode and run it again.. hope that will capture something when a buy or sell has happened

**Comment by askmike** [comment] 2017-08-19 13:01
Is gekko not doing what your strategy signals (strategy says short, gekko
does buy instead of sell)?

**Comment by krunalbarot** [comment] 2017-08-19 13:31
yes thats what it did... do not as the first signal was sell-- without any buy ?

**Comment by askmike** [comment] 2017-08-19 14:02
Strategies are not forced to start with a buy. It sounds to me like you ran
a strategy that gave signals that were not profitable?

On 19 Aug 2017 14:31, "krunalbarot" <notifications@github.com> wrote:

yes thats what it did... do not as the first signal was sell-- without any
buy ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/askmike/gekko/issues/1004#issuecomment-323523339>, or mute
the thread

**Comment by askmike** [comment] 2017-08-19 14:03
Wait, what does this mean?

"yes thats what it did... do not as the first signal was sell-- without any
buy ?"

**Comment by krunalbarot** [comment] 2017-08-19 15:46
i mean the issue  - was it because first was a sell signal --due to which it messed up things ?

**Comment by askmike** [comment] 2017-08-19 16:08
Gekko works whatever your initial balance is: if you have 1BTC and 0USD you can turn on Gekko, if the first signal is a sell signal Gekko will sell. This is not a bug but intended behaviour.

What do you mean with messed up things? That the trades were not profitable? This has to do with your strategy, read this: #201.

**Comment by krunalbarot** [comment] 2017-08-19 16:12
it is paper trade mode so nothing lost. - the thing is if first signal is sell - but if i dont have that commodity to sell in my account what will happen ?
plus messed up in the roundtrip mode - plus the strategy is simple ma crossover 10-21.. all same settings.. 
i have enabled the logs for ui,.. so will run over night and will post here with logs... :+1:

**Comment by askmike** [comment] 2017-08-19 17:50
If the first signal is sell it won't be part of the first roundtrip. But it
will be taken into account for the total profit calculation.

If you have no asset to sell no trade will be done (and as such it will not
impact profit calculation). Do note that the paper trader has it's own
(simulated) balance, you can configure it in the paper trading settings.

**Comment by raffus** [comment] 2017-08-20 02:57
Hey @askmike.
I was running Gekko UI as you know, and the UI interface was showing some entries that didn't  really happened.
In some cases it had showed some profit. Next update was with same loss.
There is a problem with the profit/loss calculator. Gekko did not go in on any trade and started showing trading (fake) results.

Before whoever might ask:
1) Was I using Gekko in multiple instances? No
2) Was I using the same account @ polo with gekko? No
3) Did Gekko got in on any advice? No
4) Did I restart gekko between any trade? No
5) Did Gekko show the entry profit/loss? No, actually it said it had no data yet;

We've gotta fix this bro. No idea about what's going on.

Count on me to do more tests.

**Comment by raffus** [comment] 2017-08-20 02:59
Also, the balance was not matching gekko's info. Somehow Gekko had wrong information. In that time-period I had not added/withdrawn any funds into/from the account.

**Comment by askmike** [comment] 2017-08-21 14:41
@krunalbarot it seems like your issue is resolved, right? As such I am closing this. If it isn't please comment here.

@raffus 

> I was running Gekko UI as you know, and the UI interface was showing some entries that didn't really happened. In some cases it had showed some profit. Next update was with same loss.

That is very strange, could you please download the latest version of Gekko (it will store logs of the UI) and as soon as it happens again create a new issue and post the logs?

**Closed as completed by askmike** 2017-08-21 14:41 UTC
