### ISSUE TITLE
Tradebot doesn't trade on candles under 1 minute in size

### ISSUE THREAD

**Issue by storshun** [askmike/gekko#2431] opened 2018-08-11 15:33 UTC
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
1. Using `node gekko --config config.js`
2. set `candle size` to a time less than 1 minute (0.5 minutes to be exact) on a tradebot connecting to Binance using CCI strategy
3. `Warmup` of 1 unit
3. Set a very large history (200+)
4. Set Up/Down variables to a `FLOAT` value (1.3/-1.5 for example)

**Expected result** (what you hoped would happen)
Back testing in gekko UI seems to function fine, I would expect candles to be 30 seconds long and trades to execute on the CCI values the market watcher finds that meet the criteria.

**Actual result** (unexpected outcome)
No trades executed, even though CCI conditions were repeatedly met according to market watcher. Adviser never gives trade advice. Conditions met several times over a 7 hour period. For instance, the following block meets the criteria for oversold and should have generated trade "Buy Order" advice:

> 2018-08-11 15:17:07 (DEBUG):    calculated CCI properties for candle:
> 2018-08-11 15:17:07 (DEBUG):             Price:          0.00067177
> 2018-08-11 15:17:07 (DEBUG):             CCI tp:         0.00067266
> 2018-08-11 15:17:07 (DEBUG):             CCI tp/n:       0.00067714
> 2018-08-11 15:17:07 (DEBUG):             CCI md:         0.00000450
> 2018-08-11 15:17:07 (DEBUG):             CCI:            -1.99 `This meets my strat criteria`
> 2018-08-11 15:17:07 (DEBUG):    Trend:  oversold  for  1

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment] 2018-08-11 17:38
Unfortunately this is a design decision and not a bug:

- Limiting candles to 1 minute makes a lot of things easier, things like persistance of trade data (in a db, default sqlite). It keeps the whole codebase a lot simpler and leaner.
- Doing stuff below 1 minute means you are not looking at macro market patterns (for which you want to use TA for example) but high frequency stuff. If you want to do this you should look at a lot more than candles (order flow, orderbook, etc). This is out of scope for Gekko and this data is currently not exposed to strategies.
- Gekko isn't designed for speed, it won't fetch trades every second so if you want tiny candles Gekko won't be able to populate them quick enough.

Please read this: https://gekko.wizb.it/docs/introduction/scope.html

**Closed as completed by askmike** 2018-08-11 17:38 UTC
Labels: invalid

**Comment by storshun** [comment] 2018-08-11 19:09
Understood, unfortunate, but I get your points. I wish the back testing had told me values less than 1 weren't valid 12 hours ago before I changed strats. :)

Thanks for the quick response, Mike. Still loving the tool.

**Comment by askmike** [comment] 2018-08-12 03:24
Good call, gekko should test whether the candlesize is a round number and
error out when it isn't.
