### ISSUE TITLE
TypeError: Cannot read property 'time' of undefined

### ISSUE THREAD

**Issue by yriveiro** [askmike/gekko#1068] opened 2017-09-01 23:18 UTC
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Fresh install and try to import local data from gdax exchange

* **Expected result** (what you hoped would happen)
I would hoped the gdax data were imported locally :D

* **Actual result** (unexpected outcome)
/mnt/data/github/gekko/exchanges/gdax.js:248
                if (moment.utc(last.time) < moment.utc(since)) {
                                   ^

TypeError: Cannot read property 'time' of undefined
    at Trader.<anonymous> (/mnt/data/github/gekko/exchanges/gdax.js:248:36)
    at Request._callback (/mnt/data/github/gekko/node_modules/gdax/lib/clients/public.js:45:7)
    at Request.self.callback (/mnt/data/github/gekko/node_modules/gdax/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/mnt/data/github/gekko/node_modules/gdax/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/mnt/data/github/gekko/node_modules/gdax/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
RECEIVED ERROR IN IMPORT 785555666701056

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment] 2017-09-01 23:48
Can you post the date range and market you were trying to import?

**Comment by discosultan** [comment] 2017-09-02 09:06
Seems to be the same as https://github.com/askmike/gekko/issues/606. There's an example config available there.

**Comment by yriveiro** [comment] 2017-09-02 09:23
@discosultan it is. 

From 2000-01-01 to 2017-09-01 was the data range used (I wanted to import the full history of Litecoin)

**Comment by askmike** [comment] 2017-09-02 13:32
Hey @yriveiro! Unfortunately GDAX didn't operate in 2000, also note that in this time no cryptocurrency actually existed.

This issue is a duplicate of #1038, unfortunately GDAX does not provide a lot of feedback to Gekko when Gekko requests market data from before there was a market, so right now it's up to the user to limit import ranges to when the market actually existed.

**Closed as completed by askmike** 2017-09-02 13:32 UTC

**Comment by yriveiro** [comment] 2017-09-02 14:46
Thanks @askmike, I know that in 2000 bitcoin was only a dream :D, I only put 2000 to be sure that I was pulling all the history data available.
