### ISSUE TITLE
okcoin.cn

### ISSUE THREAD

**Issue by jrcps** [askmike/gekko#560] opened 2017-01-22 02:41 UTC
Hi,

I have this error when I try to trade in OkCoin: "returned an error, retrying..".

**Comment by greenbigfrog** [comment] 2017-12-14 10:21
@askmike can most likely be closed (duplicate of #1008 ?)

**Comment by askmike** [comment] 2018-07-09 15:06
Unfortunately OKcoin is not enabled for now..

**Closed as completed by askmike** 2018-07-09 15:06 UTC
