### ISSUE TITLE
Gekko crashed with the following error: {"__augmented" : true}

### ISSUE THREAD

**Issue by amaner1r** [askmike/gekko#2383] opened 2018-07-29 19:38 UTC
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a Gekko User**
* Gekko bought an order in Coinbase Pro. As soon as the the order executed, error says; error: {"__augmented" : true}

**Action taken** (I researched regarding the error. I read couple posts that mentioned the problem could be due to my computer went to sleep mode. I changed the setting to never sleep. The problem has not been solved yet.)

**Comment by askmike** [comment] 2018-07-30 05:03
This issue has been plaguing some people, for mysterious reasons.. I don't think this has anything to do with your PC going to sleep.

I love to solve this but so far I have been unable to reproduce. I'm gathering all information in #2357. Can you please comment there with some more information like answers to these questions: https://github.com/askmike/gekko/issues/2357#issuecomment-408575282

Closing this here, let's keep all info in the other issue.

**Closed as completed by askmike** 2018-07-30 05:03 UTC
