### ISSUE TITLE
Tradebot does nothing on Kraken

### ISSUE THREAD

**Issue by VinceBT** [askmike/gekko#1435] opened 2017-12-07 18:33 UTC
I'm on the exchange XLM-XBT and I've let the bot run for 3 days with these settings and it does nothing but this : 
![image](https://user-images.githubusercontent.com/1362505/33731941-08f0ac92-db85-11e7-922f-f27271646f8a.png)

Here are my settings : 
![image](https://user-images.githubusercontent.com/1362505/33731948-134f1f7a-db85-11e7-9ff6-8cde8a0277dd.png)
![image](https://user-images.githubusercontent.com/1362505/33731960-1d0be5c0-db85-11e7-967f-370b51c49954.png)
![image](https://user-images.githubusercontent.com/1362505/33731982-382bbb8c-db85-11e7-8d41-2a0c74a3f183.png)
![image](https://user-images.githubusercontent.com/1362505/33732057-72f1296e-db85-11e7-948a-2a6a29fda97e.png)

**Comment by askmike** [comment] 2017-12-08 05:06
It's currently very hard to work with kraken, we are in the process of fixing this.

We just merged some changes into the develop version of Gekko that might change it, see #1411. You can try it out by downloading the develop branch of Gekko here: https://github.com/askmike/gekko/tree/develop

If you run into issues with that branch, please report them here (and specify exactly what version of Gekko you have the issues with): #1431.

Closing this as a duplicate of #1431.

**Closed as completed by askmike** 2017-12-08 05:06 UTC
