### ISSUE TITLE
[gdax.js] (getOrder) irrecoverable error: NotFound

### ISSUE THREAD

**Issue by Dalekxy** [askmike/gekko#2159] opened 2018-05-09 12:02 UTC
**I'm submitting a ...**
[X ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Live Trading with Gekko CLI

**Expected result** (what you hoped would happen)
Gekko trading without errors

**Actual result** (unexpected outcome)
Gekko returns irrecoverable error every time when order was not filled at first buy/sell price.
=> [gdax.js] (getOrder) returned an irrecoverable error: NotFound
But order is always successfully filled.
(I can't tell you if this crashes the trader since there was no second trade in my live Gekko yet.)
Edit: Trader is not crashed after irrecoverable error!
Gekko v.0.5.14 (last stable), Nodejs v.8.11.
(But also had this issue in one of the latest develop branches)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Log:
2018-05-09 12:29:17 (DEBUG):    Processing 3 new trades. From 2018-05-09 10:28:57 UTC to 2018-05-09 10:29:17 UTC. (a few seconds)
2018-05-09 12:29:17 (INFO):     Trader Received advice to go short. Selling  BTC
2018-05-09 12:29:17 (INFO):     Going short
2018-05-09 12:29:17 (INFO):     Short since 1 BEAR RSI: 50.63 ADX low
2018-05-09 12:29:17 (INFO):     Attempting to SELL 0.00130327 BTC at GDAX price: 7696.59
2018-05-09 12:29:37 (DEBUG):    Requested BTC/EUR trade data from GDAX ...
2018-05-09 12:29:37 (DEBUG):    Processing 7 new trades. From 2018-05-09 10:29:23 UTC to 2018-05-09 10:29:32 UTC. (a few seconds)
2018-05-09 12:29:57 (DEBUG):    Requested BTC/EUR trade data from GDAX ...
2018-05-09 12:29:57 (DEBUG):    Processing 3 new trades. From 2018-05-09 10:29:40 UTC to 2018-05-09 10:29:46 UTC. (a few seconds)
2018-05-09 12:30:17 (DEBUG):    Requested BTC/EUR trade data from GDAX ...
2018-05-09 12:30:17 (DEBUG):    Processing 7 new trades. From 2018-05-09 10:30:08 UTC to 2018-05-09 10:30:15 UTC. (a few seconds)
2018-05-09 12:30:18 (INFO):     SELL order was not (fully) filled, cancelling and creating new order
2018-05-09 12:30:19 (INFO):     Attempting to SELL 0.00130327 BTC at GDAX price: 7695.93
2018-05-09 12:30:37 (DEBUG):    Requested BTC/EUR trade data from GDAX ...
2018-05-09 12:30:37 (DEBUG):    Processing 1 new trades. From 2018-05-09 10:30:37 UTC to 2018-05-09 10:30:37 UTC. (a few seconds)
2018-05-09 12:30:57 (DEBUG):    Requested BTC/EUR trade data from GDAX ...
2018-05-09 12:30:57 (DEBUG):    Processing 1 new trades. From 2018-05-09 10:30:37 UTC to 2018-05-09 10:30:37 UTC. (a few seconds)
2018-05-09 12:31:17 (DEBUG):    Requested BTC/EUR trade data from GDAX ...
2018-05-09 12:31:17 (DEBUG):    Processing 1 new trades. From 2018-05-09 10:31:06 UTC to 2018-05-09 10:31:06 UTC. (a few seconds)
2018-05-09 12:31:20 (INFO):     SELL order was not (fully) filled, cancelling and creating new order
2018-05-09 12:31:21 (INFO):     Attempting to SELL 0.00130327 BTC at GDAX price: 7690.01
2018-05-09 12:31:37 (DEBUG):    Requested BTC/EUR trade data from GDAX ...
2018-05-09 12:31:37 (DEBUG):    Processing 15 new trades. From 2018-05-09 10:31:26 UTC to 2018-05-09 10:31:36 UTC. (a few seconds)
2018-05-09 12:31:57 (DEBUG):    Requested BTC/EUR trade data from GDAX ...
2018-05-09 12:31:57 (DEBUG):    Processing 1 new trades. From 2018-05-09 10:31:49 UTC to 2018-05-09 10:31:49 UTC. (a few seconds)
2018-05-09 12:32:17 (DEBUG):    Requested BTC/EUR trade data from GDAX ...
2018-05-09 12:32:17 (DEBUG):    Processing 3 new trades. From 2018-05-09 10:31:58 UTC to 2018-05-09 10:32:13 UTC. (a few seconds)
2018-05-09 12:32:21 (INFO):     SELL order was not (fully) filled, cancelling and creating new order
2018-05-09 12:32:22 (INFO):     Attempting to SELL 0.00130327 BTC at GDAX price: 7683.44
2018-05-09 12:32:37 (DEBUG):    Requested BTC/EUR trade data from GDAX ...
2018-05-09 12:32:38 (DEBUG):    Processing 1 new trades. From 2018-05-09 10:32:34 UTC to 2018-05-09 10:32:34 UTC. (a few seconds)
2018-05-09 12:32:57 (DEBUG):    Requested BTC/EUR trade data from GDAX ...
2018-05-09 12:32:57 (DEBUG):    Processing 3 new trades. From 2018-05-09 10:32:47 UTC to 2018-05-09 10:32:54 UTC. (a few seconds)
2018-05-09 12:33:17 (DEBUG):    Requested BTC/EUR trade data from GDAX ...
2018-05-09 12:33:17 (DEBUG):    Processing 8 new trades. From 2018-05-09 10:33:04 UTC to 2018-05-09 10:33:16 UTC. (a few seconds)
2018-05-09 12:33:23 (INFO):     SELL was successfull
2018-05-09 12:33:23 (ERROR):    [gdax.js] (getOrder) returned an irrecoverable error: NotFound
2018-05-09 12:33:23 (INFO):     (PROFIT REPORT) original simulated balance:      XXX EUR
2018-05-09 12:33:23 (INFO):     (PROFIT REPORT) current simulated balance:       XXX EUR
2018-05-09 12:33:23 (INFO):     (PROFIT REPORT) simulated profit:                -XXX EUR (-0.00195668%)
2018-05-09 12:33:37 (DEBUG):    Requested BTC/EUR trade data from GDAX ...
2018-05-09 12:33:37 (DEBUG):    Processing 3 new trades. From 2018-05-09 10:33:18 UTC to 2018-05-09 10:33:32 UTC. (a few seconds)
2018-05-09 12:33:57 (DEBUG):    Requested BTC/EUR trade data from GDAX ...

Having done some research, it seems to be assigned to #1852 and #1834

**Comment by askmike** [comment] 2018-07-04 15:14
That error was caused by Gekko trying to cancel an already cancelled order. This has been fixed in 0.6 Please redownload and try again :)

**Closed as completed by askmike** 2018-07-04 15:14 UTC
