### ISSUE TITLE
Issue when starting Gekko - Windows 10

### ISSUE THREAD

**Issue by prfiredragon** [askmike/gekko#1412] opened 2017-12-04 04:44 UTC
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
npm install --only=production

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)
npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--only=production"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! path /home/robert/gekko-develop/node_modules/.staging/asn1-f9d617ea
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/home/robert/gekko-develop/node_modules/.staging/asn1-f9d617ea' -> '/home/robert/gekko-develop/node_modules/sqlite3/node_modules/asn1'
npm ERR! enoent ENOENT: no such file or directory, rename '/home/robert/gekko-develop/node_modules/.staging/asn1-f9d617ea' -> '/home/robert/gekko-develop/node_modules/sqlite3/node_modules/asn1'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/robert/gekko-develop/npm-debug.log

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

The instalation of the bash.exe was diferent of the instruction. After enable the feature, the bash does't download the ubuntu. I downloaded from the market. The feature in my machine isn't a beta.

**Comment by askmike** [comment] 2017-12-05 06:29
Seems a duplicate of: https://github.com/mapbox/node-sqlite3/issues/866

Can you try some of the suggestions in that issue?

**Closed as completed** 2018-11-01 00:10 UTC
Labels: wontfix, waiting-for-answer
