### ISSUE TITLE
0.5.9 build version issue

### ISSUE THREAD

**Issue by daisy613** [askmike/gekko#1277] opened 2017-10-31 17:25 UTC
The 0.5.9 build is showing up as 0.5.8 in the web interface.  Also, no changes are apparent to the Web UI.  Perhaps forgot to compile?

**Comment by askmike** [comment] 2017-11-01 03:29
Strange, could you see if the problem is also there on latest develop branch?

**Comment by mattgauzza** [comment] 2017-11-01 17:05
This is also happening for me along with very strange data issues in the UI
https://www.screencast.com/t/o5k4f0R45o
Everything in round trips is wrong, which is causing the calculations at the top to be off as well.  The chart is accurate to the outputs in the terminal.

I can try to pull down dev branch later and will report back

**Comment by mattgauzza** [comment] 2017-11-01 20:55
After pulling down the develop branch I am seeing new buttons and some links that are now buttons.
Still having discrepancies in the back testing round trips chart
https://www.screencast.com/t/526ss0GjyRt
That might be a separate issue.
https://github.com/askmike/gekko/issues/1254#issuecomment-341241973

**Comment by askmike** [comment] 2017-11-02 03:36
@gauzzastrip 

> Everything in round trips is wrong, which is causing the calculations at the top to be off as well. The chart is accurate to the outputs in the terminal.

Besides the issue you fixed there was also an issue in the timezone conversion (all dates in the terminal and UI should be in UTC), this has since been fixed in develop as well.

-------

@dimmyr did you have a chance to check the latest develop branch?

**Closed as completed** 2018-10-31 23:22 UTC
Labels: wontfix, waiting-for-answer
