### ISSUE TITLE
kraken returned an error, retrying..

### ISSUE THREAD

**Issue by asociadoC** [askmike/gekko#1136] opened 2017-09-20 01:33 UTC
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Trading with Kraken

Trying to understand whats going on and wanted to let it do some live stuff, but seems something is going wrong. Can I see any additional info anywhere ? 

* **Expected result** (what you hoped would happen)
Working

* **Actual result** (unexpected outcome)
Not working

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

2017-09-20 00:45:20 (INFO):     trading at kraken ACTIVE
2017-09-20 00:45:20 (INFO):     kraken trading fee will be: 0.2%
2017-09-20 00:45:20 (INFO):     kraken portfolio:
2017-09-20 00:45:20 (INFO):              EUR: 73.454500000000
2017-09-20 00:45:20 (INFO):              XMR: 0.000000000000
2017-09-20 00:45:20 (INFO):     Setting up:
2017-09-20 00:45:20 (INFO):              Performance Analyzer
2017-09-20 00:45:20 (INFO):              Analyzes performances of trades
2017-09-20 00:45:20 (INFO):     

2017-09-20 00:45:20 (INFO):     Setting up:
2017-09-20 00:45:20 (INFO):              Slack
2017-09-20 00:45:20 (INFO):              Sends trades to slack channel.
2017-09-20 00:45:21 (INFO):     

2017-09-20 00:45:21 (INFO):     Starting to watch the market: Kraken XMR/EUR
2017-09-20 00:45:21 (DEBUG):    scheduling ticks
2017-09-20 00:45:21 (DEBUG):    Requested XMR/EUR trade data from Kraken ...
2017-09-20 00:45:21 (INFO):     Slack Message Sent
..
..
..
2017-09-20 00:56:21 (INFO):     We have new trading advice!
2017-09-20 00:56:21 (INFO):              Position: short
2017-09-20 00:56:21 (INFO):              Market price: 81.86
2017-09-20 00:56:21 (INFO):              Based on market time: 2017-09-20 XX:XX:XX

2017-09-20 00:56:21 (INFO):     Trader Received advice to go short. Selling  XMR
2017-09-20 00:56:22 (INFO):     Slack Message Sent
2017-09-20 00:56:23 (ERROR):    Wanted to buy EUR but the amount is too small (0.000000000000) at kraken
2017-09-20 00:56:41 (DEBUG):    Requested XMR/EUR trade data from Kraken ...
..
..
..
2017-09-20 01:20:03 (INFO):     We have new trading advice!
2017-09-20 01:20:03 (INFO):              Position: long
2017-09-20 01:20:03 (INFO):              Market price: 81.36
2017-09-20 01:20:03 (INFO):              Based on market time: 2017-09-20 01:18:00

2017-09-20 01:20:03 (INFO):     Trader Received advice to go long. Buying  XMR
2017-09-20 01:20:03 (INFO):     Slack Message Sent
2017-09-20 01:20:04 (INFO):     Attempting to BUY 0.9009505703422053 XMR at kraken price: 81.38
2017-09-20 01:20:04 (ERROR):    no data
2017-09-20 01:20:04 (DEBUG):    kraken returned an error, retrying..
2017-09-20 01:20:10 (ERROR):    no data
2017-09-20 01:20:10 (DEBUG):    kraken returned an error, retrying..

**Comment by askmike** [comment] 2017-09-20 08:37
duplicate of #1111 - let's keep the discussion in there :)

**Closed as completed by askmike** 2017-09-20 08:37 UTC
