### ISSUE TITLE
SQLITE ERROR on build a184473

### ISSUE THREAD

**Issue by BarnumD** [askmike/gekko#375] opened 2016-07-09 03:22 UTC
Got past that error but now I get this when I build against a184473
`{ Error: SQLITE_ERROR: unrecognized token: "{"
at Error (native) errno: 1, code: 'SQLITE_ERROR' }

Gekko encountered an error and can't continue

Error:

DB error at get
`

**Comment by Pascal66** [comment] 2016-07-09 08:23
same (with sqlite 3.1.3 or 3.1.4: 

2016-07-09 10:22:21 (INFO):

2016-07-09 10:22:21 (INFO):     Setting up:
2016-07-09 10:22:21 (INFO):              Trading Advisor
2016-07-09 10:22:21 (INFO):              Calculate trading advice
2016-07-09 10:22:21 (INFO):

{ Error: SQLITE_ERROR: unrecognized token: "{"
    at Error (native) errno: 1, code: 'SQLITE_ERROR' }

Gekko encountered an error and can't continue

Error:

DB error at `get`

Meta debug info:

Gekko version: v0.3.1
Nodejs version: v6.3.0

**Comment by Niller2005** [comment] 2016-07-09 15:40
I just deleted the history folder and it works.

**Comment by askmike** [comment] 2016-07-09 16:58
Could you send me the database file of the exchange you are trying to use? Also what OS are you on?

**Comment by BarnumD** [comment] 2016-07-09 17:07
I'm running on Ubuntu 14, inside a node docker container.  This is the dockerfile configuration:
`FROM node:6

RUN mkdir -p /usr/src/gekko
WORKDIR /usr/src/gekko

#Download & setup Gekko trading bot
RUN git clone -b develop https://github.com/askmike/gekko.git .; \
    git reset --hard a1844738d86ea44797e993bef8e0c2a49e428463; \
    npm install

#Enable redis plugin
RUN npm install redis@0.10.0

CMD [ "node", "gekko" ]`

**Comment by BarnumD** [comment] 2016-07-09 17:18
Hmm.. I'm unable to reproduce that error at the moment.  I think I'm actually going to change the docker container so that you can run inside the container more easily without the gekko process running at the same time.  You can leave this closed for now.  Thanks.

**Comment by Niller2005** [comment] 2016-07-09 18:26
https://www.dropbox.com/s/gonqii1ypz74edt/bitfinex_0.1.db?dl=0
OS:  Ubuntu 14.04.4 LTS

**Comment by Pascal66** [comment] 2016-07-10 06:29
All is working after renaming/deleting history folder after changing from nodejs5 to nodejs6 and git pull

**Comment by askmike** [comment] 2016-07-10 18:22
Very weird, I am not able to reproduce. Could it be caused by not running `npm install` after upgrading nodejs (and thus running an binary build for an old verison of nodejs against node6)?

**Comment by askmike** [comment] 2016-07-10 18:23
@Niller2005 could you share me your config as well, together with an output of `npm list`? As well as when was the time you last ran `npm install` (before or after upgrading nodejs)? I am closing for now, as I am unable to reproduce.

**Comment by Niller2005** [comment] 2016-07-10 20:29
Config: http://pastebin.com/WjUSkHn8
npm list: http://pastebin.com/eKu4FDPr
npm install: after upgrading

**Comment by eauel** [comment] 2016-07-10 20:40
I am having this issue as well.  I am currently on commit aa169f7851a2ab668882b8f2be7d1f8caedfadbc.

It happens for me whenever I run Gekko, stop it (Ctrl-C), **then re-run it**.
[Config](http://pastebin.com/kQPBdsEv)
[Log (Console Output)](http://pastebin.com/sfLhbG9W)
[npm list](http://pastebin.com/N3SP6apC)

I ran `npm install` after pulling to this commit.

If I delete my history folder and try running, it works fine again (until stopping and re-running again).

**Comment by askmike** [comment] 2016-07-10 20:50
@eauel are you also on ubuntu?

**Comment by eauel** [comment] 2016-07-10 21:02
@askmike I am running ArchLinux on a Raspberry Pi (armv6h)

`uname -r`
4.4.14-1-ARCH

**Comment by BarnumD** [comment] 2016-07-10 21:06
That's probably similar to me in that I use docker and often stop the
container without thinking about properly stopping the app.  Does node
listen to HUP requests?

**Closed as completed** 2016-07-10 21:59 UTC

**Comment by askmike** [comment] 2016-07-10 22:01
I figured it out! I did not properly update a codepath which is seldom walked after changing the way historical data from the sqlite database was passed around. I tested a lot using the backtesting mode, however I didn't properly test this..

**Comment by eauel** [comment] 2016-07-11 00:56
Just updated and tried running it again, and so far it's working well; thanks!

**Comment by BarnumD** [comment] 2016-07-11 02:45
Same.

**Comment by Pascal66** [comment] 2016-07-11 05:53
Updated and worked.
Is it possible to reimport the old history base wich i have renamed to made it work as say before, to the new actual base?

**Comment by askmike** [comment] 2016-07-11 09:11
Awesome!

> Is it possible to reimport the old history base wich i have renamed to made it work as say before, to the new actual base?

You can rename it back and Gekko will start using it (there was a bug in the query code, the data itself is not corrupted).

As for combining all data: Gekko has no way to merge sqlite databases. But if you really want to (so you can backtest etc), let me know and I'll write a quick script that copies all data from one into another.

**Comment by Pascal66** [comment] 2016-07-11 09:42
I think it can be not usefull, because it was a 'long' time between the moment i've backed it and started with an empty history folder. So it will be missing almost 1 day of datas.
