### ISSUE TITLE
[ERROR] Binance Live Trade: Timestamp for this request was 1000ms ahead of the server's time

### ISSUE THREAD

**Issue by ansonphong** [askmike/gekko#1855] opened 2018-02-04 07:18 UTC
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report ?

* **Action taken** (what you did)
Run live trader on Binance.

* **Actual result** (unexpected outcome)
Node crashes, with the following error:

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

```
2018-02-03 20:56:12 (INFO):     Attempting to BUY 7.89 NEO at binance price: 0.128
2018-02-03 20:56:12 (DEBUG):    [binance.js] (addOrder) BUY 7.89 NEO @0.128 ETH
2018-02-03 20:56:12 (ERROR):    [binance.js] (addOrder) returned an irrecoverable error: Error: Response code 400
2018-02-03 20:56:12 (DEBUG):    [binance.js] entering "setOrder" callback after api call, err: [binance.js] Response code 400 data: {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}

Gekko encountered an error and can't continue

Error:
[binance.js] Response code 400

Meta debug info:

Gekko version: v0.5.13
Nodejs version: v8.9.3
```

This is very strange, it's a non-persistent issue, so it's happened about 4-5 times in a row, sometimes after a few hours trading, sometimes right away after starting the trader. I reset the time on my computer and it seems to be working now (maybe, we will see for how long). It's only happening on one of my strategies on 5M candles, not ones running on the same system on 1M candles.

Does anybody have any ideas about this? It would be nice to continue to make Gekko more reliable or be able to deal with this kind of anomalies. Is it related to my internet connection perhaps or my local clock? Not sure what to make of this. Thanks.

**Comment by askmike** [comment] 2018-02-04 08:58
There have been a ton of issues specifically with Binance in the past. It's pretty stable now (compared to a few weeks back)..

Pinging @cmroche & @aarongarvey

**Comment by zoeyg** [comment] 2018-02-06 05:29
Are thing setup such that they only utilize `(start|end)TimeSync`?  If you pass a `handleDrift: true` as part of the options to the constructor it will retry the request after calculating the drift.  It will only reattempt a request once though.  If it's still failing after that you must have a very inconsistent network.

**Comment by TadejPanjtar** [comment] 2018-02-08 19:27
I found this error reproducible on Windows. On Linux works fine.

**Comment by cmroche** [comment] 2018-02-10 20:07
@aarongarvey @askmike We are using the drift calculations, at least on the develop branch.

@TadejPanjtar SYnc the develop branch and confirm with that code please.

**Comment by zoeyg** [comment] 2018-02-10 20:31
Just took a look at the develop branch and wanted to be clear about the two mechanisms that were implemented for handling the drift so you can make an informed decision about how to handle things.  The two mechanisms can work in tandem, and it doesn't look like the develop branch has `handleDrift: true`, only `startTimeSync.`

For `startTimeSync` I setup the calculation on an interval so that once a request is sent it either goes through or fails, and hopefully goes through because you're syncing periodically.  The idea being that if requests are very time sensitive, you may not want to wait for an extra round trip to get the server time and then retrying the request.  However, if someone syncs their clock and it causes a significant change to the time in the middle of one of those intervals it will throw off the drift and any subsequent requests before the next calculation.

Which is why I also implemented the `handleDrift` option.  If you're going for increased stability and don't care about the request succeeding or failing really quickly, turning it on will cause requests that hit the time errors to trigger a drift calculation and then a reattempt of the original request.  If that second request fails, that's when it'll bubble the error up out of the library.

So if you're using both together, you should hopefully get the quickest request times, but also be covered in case of the clock syncing in between intervals.

**Comment by cmroche** [comment] 2018-02-11 21:25
@aarongarvey Ah ok good to know. I didn't catch that when I was looking through the implementation, and so I'll make a fix soon.

**Comment by TadejPanjtar** [comment] 2018-02-12 08:09
Test from the develop branch now works just fine on win10.

**Comment by askmike** [comment] 2018-02-12 08:17
thanks @cmroche for the fix.

Closing this as fixed. If anything else comes up please open a new issue.

**Closed as completed by askmike** 2018-02-12 08:17 UTC
Labels: bug, exchange
