### ISSUE TITLE
StochRSI wrong calculation?

### ISSUE THREAD

**Issue by jonathandezoete** [askmike/gekko#1120] opened 2017-09-15 16:27 UTC
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
used the stochrsi strat as indicator

* **Expected result** (what you hoped would happen)
get correct stoch rsi graph :)

* **Actual result** (unexpected outcome)
got incorrect values (maybe)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Hi, Im new to trading, but experienced in programming. I used the stochRsi strat to create an indicator (so i can plot it on the graph). However, i was looking at the calculation code and i saw it uses the RSI history to create the stochRSI. However, when i look at the formula, it should not use the _.min(rsi) and _max(rsi), but the highest high and the lowest low.

I don't really know the impact of the difference in calculation. maybe someone with more trading experience knows if it's worth it to update.

**Comment by askmike** [comment] 2017-09-15 16:31
ping @SamThomp: would you know this? :)

**Comment by John1231983** [comment] 2017-11-09 02:24
Hello, I also have the same issue. I compare the value of Gekko and tradeview tool. Tradeview tool returns  around 40% but stochRSI returns 100. This is output

```
2017-11-09 11:21:46 (DEBUG):	Processing 2 new trades. From 2017-11-09 02:21:09 UTC to 2017-11-09 02:21:09 UTC. (a few seconds)
2017-11-09 11:21:46 (DEBUG):	calculated StochRSI properties for candle:
2017-11-09 11:21:46 (DEBUG):		 rsi: 52.42888997
2017-11-09 11:21:46 (DEBUG):	StochRSI min:		31.92704552
2017-11-09 11:21:46 (DEBUG):	StochRSI max:		52.42888997
2017-11-09 11:21:46 (DEBUG):	StochRSI Value:		100.00

```
// StochRSI settings
```
config.StochRSI = {
  interval: 14,
  thresholds: {
    low: 20,
    high: 80,
    // How many candle intervals should a trend persist
    // before we consider it real?
    persistence: 3
  }
};
```
This is an example

![untitled](https://user-images.githubusercontent.com/24875971/32585998-a06c61ae-c543-11e7-8ec6-b34aca337dc4.png)

**Comment by rkingy** [comment] 2018-01-12 07:08
Hi Guys,

I found the same issue and found a fix after many hours of faffing around.. the problem is that the stochRSI formula is correct but the indicator in TradingView creates two SMA (Simple moving averages) of these values which are called %K and %D (which is a SMA of %K) these are the two lines that cross over each other in TradingView.

Attached is my re-vamp of the file where I've rebuilt the method.update
But haven't rebuilt the method.check here.. I'll leave that for someone else as I'm using this logic in another script I'm building.

I hope this helps someone else!


```
// helpers
var _ = require('lodash');
var log = require('../core/log.js');

var RSI = require('./indicators/RSI.js');
var SMA = require('./indicators/SMA.js');

// let's create our own method
var method = {};

// prepare everything our method needs
method.init = function() {
  this.interval = this.settings.interval;

  this.trend = {
    direction: 'none',
    duration: 0,
    persisted: false,
    adviced: false
  };

  this.requiredHistory = this.tradingAdvisor.historySize;

  // define the indicators we need
  this.addIndicator('rsi', 'RSI', { interval: this.interval });

	this.RSIhistory = [];
	
	this.fastrsi = new SMA(3);
	this.slowrsi = new SMA(3);
}

// what happens on every new candle?
method.update = function(candle) {
	this.rsi = this.indicators.rsi.result;

	this.RSIhistory.push(this.rsi);

	if(_.size(this.RSIhistory) > this.interval){
		// remove oldest RSI value
		this.RSIhistory.shift();
	}

	this.lowestRSI = _.min(this.RSIhistory);
	this.highestRSI = _.max(this.RSIhistory);
	this.stochRSI = ((this.rsi - this.lowestRSI) / (this.highestRSI - this.lowestRSI)) * 100;
	if(!isNaN(this.stochRSI)){//Only put numbers in here
		this.fastrsi.update(this.stochRSI);
	}
	if(!isNaN(this.fastrsi.result)){//Only put numbers in here
		this.slowrsi.update(this.fastrsi.result);
	}
	
}
```

Use this.fastrsi.result for the blue line and this.slowrsi.result for the red line as per the graph in TradingView

**Comment by ScottHollows** [comment] 2018-03-30 00:27
rkingy - how did you get the source code for StochRSI on TradingView ?  I want to try out a variation of that, but I cant work out how to get the source for the built in functions like StochRSI

Thank you :)

**Comment by rkingy** [comment] 2018-04-02 22:00
@ScottHollows TradingView has a Wiki site page for each indicator. Just google "stoch rsi tradingview wiki" and you'll find it.

https://www.tradingview.com/wiki/Stochastic_RSI_(STOCH_RSI)

**Comment by swanfield1979** [comment] 2018-04-27 20:50
Ok, the problem I have is that what I see in tradeview is not what I see in PT2. I have changed everything updated and it still seems to be off imo.

If it is working, could you explain how I could see the same results in TV as in PT2?

**Comment by rkingy** [comment] 2018-04-29 21:37
Make sure the timezone in trading view is set to GMT

**Comment by ezgoProject** [comment] 2018-09-20 01:35
> Make sure the timezone in trading view is set to GMT

The code doesn't work well. I try to fix it, but I can't solve the problem.

**Comment by rkingy** [comment] 2018-09-20 01:40
> The code doesn't work well. I try to fix it, but I can't solve the problem.

Can you get the RSI indicator producing the correct results? Make sure this is outputting the correct results first.

**Comment by ezgoProject** [comment] 2018-09-20 04:20
> > The code doesn't work well. I try to fix it, but I can't solve the problem.
> 
> Can you get the RSI indicator producing the correct results? Make sure this is outputting the correct results first.

I don't think so. I think this.fastrsi = new SMA(3);
	this.slowrsi = new SMA(3); doesn't work.

**Comment by rkingy** [comment] 2018-09-20 04:32
> > > The code doesn't work well. I try to fix it, but I can't solve the problem.
> > 
> > 
> > Can you get the RSI indicator producing the correct results? Make sure this is outputting the correct results first.
> 
> I don't think so. I think this.fastrsi = new SMA(3);
> this.slowrsi = new SMA(3); doesn't work.

Do you have 
var SMA = require('./indicators/SMA.js');
At the top of your script? And do you have SMA.js in your indicators folder?

**Comment by ezgoProject** [comment] 2018-09-20 04:56
> > > > The code doesn't work well. I try to fix it, but I can't solve the problem.
> > > 
> > > 
> > > Can you get the RSI indicator producing the correct results? Make sure this is outputting the correct results first.
> > 
> > 
> > I don't think so. I think this.fastrsi = new SMA(3);
> > this.slowrsi = new SMA(3); doesn't work.
> 
> Do you have
> var SMA = require('./indicators/SMA.js');
> At the top of your script? And do you have SMA.js in your indicators folder?

// helpers
var _ = require('lodash');
var log = require('../core/log.js');

var RSI = require('./indicators/RSI.js');
var SMA = require('./indicators/SMA.js');

// let's create our own method
var method = {};

// prepare everything our method needs
method.init = function() {
	this.name="StochRSI";
	log.info("fucntion initiate");
  this.interval = this.settings.interval;

  this.trend = {
    direction: 'none',
    duration: 0,
    persisted: false,
    adviced: false
  };

  this.requiredHistory = this.tradingAdvisor.historySize;

  // define the indicators we need
  this.addIndicator('rsi', 'RSI', { interval: this.interval });
  this.addIndicator('fastrsi', 'SMA', 3);
this.addIndicator('slowrsi', 'SMA', 3);
this.RSIhistory = [];

}


// what happens on every new candle?
method.update = function(candle) {
	this.fastrsi = this.indicators.fastrsi.result;
	this.slowrsi = this.indicators.slowrsi.result;
this.rsi = this.indicators.rsi.result;

this.RSIhistory.push(this.rsi);

if(_.size(this.RSIhistory) > this.interval){
// remove oldest RSI value
this.RSIhistory.shift();
}

this.lowestRSI = _.min(this.RSIhistory);
this.highestRSI = _.max(this.RSIhistory);
this.stochRSI = ((this.rsi - this.lowestRSI) / (this.highestRSI - this.lowestRSI)) * 100;

if(!isNaN(this.stochRSI)){//Only put numbers in here
this.fastrsi.update(this.stochRSI);
}
if(!isNaN(fastrsi)){//Only put numbers in here
this.slowrsi.update(this.fastrsi);
}
log.info("lfastrsi:"+fastrsi);
}

**Comment by ezgoProject** [comment] 2018-09-20 04:57
Error:

No init function in this trading method found.

I also get this message

**Comment by rkingy** [comment] 2018-09-20 08:32
> Error:
> 
> No init function in this trading method found.
> 
> I also get this message

Oh ok, well the code snipped I gave above was just a partial strategy code example. The idea was that you can just copy these parts into your existing working strategy.
I've created a little template strategy for you and attached it. It won't make you any money but it will hopefully point you in the right direction.


[StochRSI_rkingy.js.zip](https://github.com/askmike/gekko/files/2400434/StochRSI_rkingy.js.zip)

**Comment by askmike** [comment] 2018-09-20 09:02
@rkingy @ezgoProject this is a very old thread. Feel free to keep discussing custom threads. But I'm closing the issue (you can keep discussing). I do think the strategy section on the forum ( https://forum.gekko.wizb.it/ ) would be a better place for this discussion.

**Closed as completed by askmike** 2018-09-20 09:02 UTC
