### ISSUE TITLE
Build Errors: Linux

### ISSUE THREAD

**Issue by QuadroBro** [askmike/gekko#855] opened 2017-07-17 16:57 UTC
Hi, I'm trying to get this built and running, but it's kicking out errors. Any idea which dependency I'm missing or it's not finding here? Additionally, when I run it, it appears to run but when I try to access it on my VPS it appears not to be running. Can this only be accessed using "localhost"?

![gekkobuilderrors](https://user-images.githubusercontent.com/18014060/28279729-a9e503d6-6ade-11e7-8f43-f80321311c9b.png)

**Comment by askmike** [comment] 2017-07-17 18:17
> Any idea which dependency I'm missing or it's not finding here?

It complains about `make` it seems, what distro are you running?

> Additionally, when I run it, it appears to run but when I try to access it on my VPS it appears not to be running. Can this only be accessed using "localhost"?

For that you have to properly configure the UI config, see here: https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html

There are 3 ways to run the Gekko UI:

- on your computer (view where it is running)
- on an external machine, but in a fully trusted network (raspberry PI, etc)
- on an external machine, in the cloud

For the last one you probably want to add some kind of authentication (between your browser and the Gekko process), an example of using nginx for that is provided in the link.

**Comment by QuadroBro** [comment] 2017-07-17 19:08
I'm running ubuntu 17.1.

**Comment by askmike** [comment] 2017-07-20 11:23
Can you quickly check whether node and nmp are installed correctly? Please post the output of:

    node -v
    npm -v

**Comment by askmike** [comment] 2017-07-25 22:23
Closing this, as I cannot reproduce..

**Closed as completed by askmike** 2017-07-25 22:23 UTC
Labels: waiting-for-answer, cannot-reproduce
