### ISSUE TITLE
Getting gekko run in google cloud returned WebSocket connection to failed: Error

### ISSUE THREAD

**Issue by gauravkhrnr** [askmike/gekko#1079] opened 2017-09-04 11:14 UTC
**bug report**
I hosted and run gekko on google cloud but when I hit url it gives following error ... 

![wserror](https://user-images.githubusercontent.com/20242899/30024200-489636a8-9190-11e7-8c86-412e3c1d5469.png)

**Comment by askmike** [comment] 2017-09-04 12:02
Hey! @gauravkhrnr it seems you are having some issues installing Gekko in the cloud (to be exact: #1052, #1055, #1057, #1062, #1071 and this one). **Please don't open new issues, but comment on any old one (this one for example).**

The problem is that you have not configured the UIConfig properly. You have configured the UI to be 127.0.0.1, but in the screenshot you can see that your Gekko is actually running on `104.192.159.226`. Please configure it accordingly as stated here: https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html

**Comment by askmike** [comment] 2017-09-04 12:02
I am closing this because it's not an issue with Gekko, but feel free to keep replying if you have more issues.

**Closed as completed by askmike** 2017-09-04 12:02 UTC

**Comment by gauravkhrnr** [comment] 2017-09-04 12:56
thank you mike

**Comment by calixjabs** [comment] 2018-03-04 14:14
please @ gauravkhrnr can you give me the steps you took in getting gekko run on Google cloud .. 

thanks in advance
