### ISSUE TITLE
is working properly ??

### ISSUE THREAD

**Issue by trincaxt** [askmike/gekko#440] opened 2016-09-08 05:47 UTC
I'm sorry so lay in the subject like this is running fine and that way he buy and sell?

because I do not see running purchase order and not for sale how can proceed properly?

```
:\Users\Trincax\Desktop\Nova pasta (6)\gekko-stable>node gekko
2016-09-08 02:35:45 (INFO):     Gekko v0.3.2 started
2016-09-08 02:35:45 (INFO):     I'm gonna make you rich, Bud Fox.


2016-09-08 02:35:45 (INFO):     Setting up Gekko in realtime mode
2016-09-08 02:35:45 (INFO):
2016-09-08 02:35:45 (INFO):     Setting up:
2016-09-08 02:35:45 (INFO):              Candle writer
2016-09-08 02:35:45 (INFO):              Store candles in a database
2016-09-08 02:35:45 (INFO):

2016-09-08 02:35:45 (INFO):     Setting up:
2016-09-08 02:35:45 (INFO):              Trading Advisor
2016-09-08 02:35:45 (INFO):              Calculate trading advice
2016-09-08 02:35:45 (DEBUG):    The trading method requests 90000 seconds of historic data. Checking availablity..
2016-09-08 02:35:45 (INFO):

2016-09-08 02:35:49 (DEBUG):    Exchange has data spanning 749 seconds, we need at least 90000 seconds.
2016-09-08 02:35:49 (INFO):              Unable to seed the trading method with locally stored historical candles (Gekko needs more time before it can give advice).
2016-09-08 02:35:49 (INFO):              Using the trading method: MACD
2016-09-08 02:35:49 (WARN):     Warning, trading method has no name
2016-09-08 02:35:49 (INFO):     Setting up:
2016-09-08 02:35:49 (INFO):              Trader
2016-09-08 02:35:49 (INFO):              Follows the advice and create real orders.
2016-09-08 02:35:49 (DEBUG):    getting balance & fee from Poloniex
2016-09-08 02:35:49 (INFO):

2016-09-08 02:35:52 (INFO):     trading at Poloniex ACTIVE
2016-09-08 02:35:52 (INFO):     Poloniex trading fee will be: 0.25%
2016-09-08 02:35:52 (INFO):     Poloniex portfolio:
2016-09-08 02:35:52 (INFO):              1CR: 0
2016-09-08 02:35:52 (INFO):              ABY: 0
2016-09-08 02:35:52 (INFO):              AC: 0
2016-09-08 02:35:52 (INFO):              ACH: 0
2016-09-08 02:35:52 (INFO):              ADN: 0
2016-09-08 02:35:52 (INFO):              AEON: 0
2016-09-08 02:35:52 (INFO):              AERO: 0
2016-09-08 02:35:52 (INFO):              AIR: 0
2016-09-08 02:35:52 (INFO):              AMP: 0
2016-09-08 02:35:52 (INFO):              APH: 0
2016-09-08 02:35:52 (INFO):              ARCH: 0
2016-09-08 02:35:52 (INFO):              AUR: 0
2016-09-08 02:35:52 (INFO):              AXIS: 0
2016-09-08 02:35:52 (INFO):              BALLS: 0
2016-09-08 02:35:52 (INFO):              BANK: 0
2016-09-08 02:35:52 (INFO):              BBL: 0
2016-09-08 02:35:52 (INFO):              BBR: 0
2016-09-08 02:35:52 (INFO):              BCC: 0
2016-09-08 02:35:52 (INFO):              BCN: 0
2016-09-08 02:35:52 (INFO):              BCY: 0
2016-09-08 02:35:52 (INFO):              BDC: 0
2016-09-08 02:35:52 (INFO):              BDG: 0
2016-09-08 02:35:52 (INFO):              BELA: 0
2016-09-08 02:35:52 (INFO):              BITCNY: 0
2016-09-08 02:35:52 (INFO):              BITS: 0
2016-09-08 02:35:52 (INFO):              BITUSD: 0
2016-09-08 02:35:52 (INFO):              BLK: 0
2016-09-08 02:35:52 (INFO):              BLOCK: 0
2016-09-08 02:35:52 (INFO):              BLU: 0
2016-09-08 02:35:52 (INFO):              BNS: 0
2016-09-08 02:35:52 (INFO):              BONES: 0
2016-09-08 02:35:52 (INFO):              BOST: 0
2016-09-08 02:35:52 (INFO):              BTC: 0.02306905
2016-09-08 02:35:52 (INFO):              BTCD: 0
2016-09-08 02:35:52 (INFO):              BTCS: 0
2016-09-08 02:35:52 (INFO):              BTM: 0
2016-09-08 02:35:52 (INFO):              BTS: 0
2016-09-08 02:35:52 (INFO):              BURN: 0
2016-09-08 02:35:52 (INFO):              BURST: 0
2016-09-08 02:35:52 (INFO):              C2: 0
2016-09-08 02:35:52 (INFO):              CACH: 0
2016-09-08 02:35:52 (INFO):              CAI: 0
2016-09-08 02:35:52 (INFO):              CC: 0
2016-09-08 02:35:52 (INFO):              CCN: 0
2016-09-08 02:35:52 (INFO):              CGA: 0
2016-09-08 02:35:52 (INFO):              CHA: 0
2016-09-08 02:35:52 (INFO):              CINNI: 0
2016-09-08 02:35:52 (INFO):              CLAM: 0
2016-09-08 02:35:52 (INFO):              CNL: 0
2016-09-08 02:35:52 (INFO):              CNMT: 0
2016-09-08 02:35:52 (INFO):              CNOTE: 0
2016-09-08 02:35:52 (INFO):              COMM: 0
2016-09-08 02:35:52 (INFO):              CON: 0
2016-09-08 02:35:52 (INFO):              CORG: 0
2016-09-08 02:35:52 (INFO):              CRYPT: 0
2016-09-08 02:35:52 (INFO):              CURE: 0
2016-09-08 02:35:52 (INFO):              CYC: 0
2016-09-08 02:35:52 (INFO):              DAO: 0
2016-09-08 02:35:52 (INFO):              DASH: 0
2016-09-08 02:35:52 (INFO):              DCR: 0
2016-09-08 02:35:52 (INFO):              DGB: 0
2016-09-08 02:35:52 (INFO):              DICE: 0
2016-09-08 02:35:52 (INFO):              DIEM: 0
2016-09-08 02:35:52 (INFO):              DIME: 0
2016-09-08 02:35:52 (INFO):              DIS: 0
2016-09-08 02:35:52 (INFO):              DNS: 0
2016-09-08 02:35:52 (INFO):              DOGE: 0
2016-09-08 02:35:52 (INFO):              DRKC: 0
2016-09-08 02:35:52 (INFO):              DRM: 0
2016-09-08 02:35:52 (INFO):              DSH: 0
2016-09-08 02:35:52 (INFO):              DVK: 0
2016-09-08 02:35:52 (INFO):              EAC: 0
2016-09-08 02:35:52 (INFO):              EBT: 0
2016-09-08 02:35:52 (INFO):              ECC: 0
2016-09-08 02:35:52 (INFO):              EFL: 0
2016-09-08 02:35:52 (INFO):              EMC2: 0
2016-09-08 02:35:52 (INFO):              EMO: 0
2016-09-08 02:35:52 (INFO):              ENC: 0
2016-09-08 02:35:52 (INFO):              ETC: 0
2016-09-08 02:35:52 (INFO):              ETH: 0
2016-09-08 02:35:52 (INFO):              eTOK: 0
2016-09-08 02:35:52 (INFO):              EXE: 0
2016-09-08 02:35:52 (INFO):              EXP: 0
2016-09-08 02:35:52 (INFO):              FAC: 0
2016-09-08 02:35:52 (INFO):              FCN: 0
2016-09-08 02:35:52 (INFO):              FCT: 0
2016-09-08 02:35:52 (INFO):              FIBRE: 0
2016-09-08 02:35:52 (INFO):              FLAP: 0
2016-09-08 02:35:52 (INFO):              FLDC: 0
2016-09-08 02:35:52 (INFO):              FLO: 0
2016-09-08 02:35:52 (INFO):              FLT: 0
2016-09-08 02:35:52 (INFO):              FOX: 0
2016-09-08 02:35:52 (INFO):              FRAC: 0
2016-09-08 02:35:52 (INFO):              FRK: 0
2016-09-08 02:35:52 (INFO):              FRQ: 0
2016-09-08 02:35:52 (INFO):              FVZ: 0
2016-09-08 02:35:52 (INFO):              FZ: 0
2016-09-08 02:35:52 (INFO):              FZN: 0
2016-09-08 02:35:52 (INFO):              GAME: 0
2016-09-08 02:35:52 (INFO):              GAP: 0
2016-09-08 02:35:52 (INFO):              GDN: 0
2016-09-08 02:35:52 (INFO):              GEMZ: 0
2016-09-08 02:35:52 (INFO):              GEO: 0
2016-09-08 02:35:52 (INFO):              GIAR: 0
2016-09-08 02:35:52 (INFO):              GLB: 0
2016-09-08 02:35:52 (INFO):              GML: 0
2016-09-08 02:35:52 (INFO):              GNS: 0
2016-09-08 02:35:52 (INFO):              GOLD: 0
2016-09-08 02:35:52 (INFO):              GPC: 0
2016-09-08 02:35:52 (INFO):              GPUC: 0
2016-09-08 02:35:52 (INFO):              GRC: 0
2016-09-08 02:35:52 (INFO):              GRCX: 0
2016-09-08 02:35:52 (INFO):              GRS: 0
2016-09-08 02:35:52 (INFO):              GUE: 0
2016-09-08 02:35:52 (INFO):              H2O: 0
2016-09-08 02:35:52 (INFO):              HIRO: 0
2016-09-08 02:35:52 (INFO):              HOT: 0
2016-09-08 02:35:52 (INFO):              HUC: 0
2016-09-08 02:35:52 (INFO):              HUGE: 0
2016-09-08 02:35:52 (INFO):              HVC: 0
2016-09-08 02:35:52 (INFO):              HYP: 0
2016-09-08 02:35:52 (INFO):              HZ: 0
2016-09-08 02:35:52 (INFO):              IFC: 0
2016-09-08 02:35:52 (INFO):              INDEX: 0
2016-09-08 02:35:52 (INFO):              IOC: 0
2016-09-08 02:35:52 (INFO):              ITC: 0
2016-09-08 02:35:52 (INFO):              IXC: 0
2016-09-08 02:35:52 (INFO):              JLH: 0
2016-09-08 02:35:52 (INFO):              JPC: 0
2016-09-08 02:35:52 (INFO):              JUG: 0
2016-09-08 02:35:52 (INFO):              KDC: 0
2016-09-08 02:35:52 (INFO):              KEY: 0
2016-09-08 02:35:52 (INFO):              LBC: 0
2016-09-08 02:35:52 (INFO):              LC: 0
2016-09-08 02:35:52 (INFO):              LCL: 0
2016-09-08 02:35:52 (INFO):              LEAF: 0
2016-09-08 02:35:52 (INFO):              LGC: 0
2016-09-08 02:35:52 (INFO):              LOL: 0
2016-09-08 02:35:52 (INFO):              LOVE: 0
2016-09-08 02:35:52 (INFO):              LQD: 0
2016-09-08 02:35:52 (INFO):              LSK: 0
2016-09-08 02:35:52 (INFO):              LTBC: 0
2016-09-08 02:35:52 (INFO):              LTC: 0
2016-09-08 02:35:52 (INFO):              LTCX: 0
2016-09-08 02:35:52 (INFO):              MAID: 0
2016-09-08 02:35:52 (INFO):              MAST: 0
2016-09-08 02:35:52 (INFO):              MAX: 0
2016-09-08 02:35:52 (INFO):              MCN: 0
2016-09-08 02:35:52 (INFO):              MEC: 0
2016-09-08 02:35:52 (INFO):              METH: 0
2016-09-08 02:35:52 (INFO):              MIL: 0
2016-09-08 02:35:52 (INFO):              MIN: 0
2016-09-08 02:35:52 (INFO):              MINT: 0
2016-09-08 02:35:52 (INFO):              MMC: 0
2016-09-08 02:35:52 (INFO):              MMNXT: 0
2016-09-08 02:35:52 (INFO):              MMXIV: 0
2016-09-08 02:35:52 (INFO):              MNTA: 0
2016-09-08 02:35:52 (INFO):              MON: 0
2016-09-08 02:35:52 (INFO):              MRC: 0
2016-09-08 02:35:52 (INFO):              MRS: 0
2016-09-08 02:35:52 (INFO):              MTS: 0
2016-09-08 02:35:52 (INFO):              MUN: 0
2016-09-08 02:35:52 (INFO):              MYR: 0
2016-09-08 02:35:52 (INFO):              MZC: 0
2016-09-08 02:35:52 (INFO):              N5X: 0
2016-09-08 02:35:52 (INFO):              NAS: 0
2016-09-08 02:35:52 (INFO):              NAUT: 0
2016-09-08 02:35:52 (INFO):              NAV: 0
2016-09-08 02:35:52 (INFO):              NBT: 0
2016-09-08 02:35:52 (INFO):              NEOS: 0
2016-09-08 02:35:52 (INFO):              NL: 0
2016-09-08 02:35:52 (INFO):              NMC: 0
2016-09-08 02:35:52 (INFO):              NOBL: 0
2016-09-08 02:35:52 (INFO):              NOTE: 0
2016-09-08 02:35:52 (INFO):              NOXT: 0
2016-09-08 02:35:52 (INFO):              NRS: 0
2016-09-08 02:35:52 (INFO):              NSR: 0
2016-09-08 02:35:52 (INFO):              NTX: 0
2016-09-08 02:35:52 (INFO):              NXT: 0
2016-09-08 02:35:52 (INFO):              NXTI: 0
2016-09-08 02:35:52 (INFO):              OMNI: 0
2016-09-08 02:35:52 (INFO):              OPAL: 0
2016-09-08 02:35:52 (INFO):              PAND: 0
2016-09-08 02:35:52 (INFO):              PAWN: 0
2016-09-08 02:35:52 (INFO):              PIGGY: 0
2016-09-08 02:35:52 (INFO):              PINK: 0
2016-09-08 02:35:52 (INFO):              PLX: 0
2016-09-08 02:35:52 (INFO):              PMC: 0
2016-09-08 02:35:52 (INFO):              POT: 0
2016-09-08 02:35:52 (INFO):              PPC: 0
2016-09-08 02:35:52 (INFO):              PRC: 0
2016-09-08 02:35:52 (INFO):              PRT: 0
2016-09-08 02:35:52 (INFO):              PTS: 0
2016-09-08 02:35:52 (INFO):              Q2C: 0
2016-09-08 02:35:52 (INFO):              QBK: 0
2016-09-08 02:35:52 (INFO):              QCN: 0
2016-09-08 02:35:52 (INFO):              QORA: 0
2016-09-08 02:35:52 (INFO):              QTL: 0
2016-09-08 02:35:52 (INFO):              RADS: 0
2016-09-08 02:35:52 (INFO):              RBY: 0
2016-09-08 02:35:52 (INFO):              RDD: 0
2016-09-08 02:35:52 (INFO):              RIC: 0
2016-09-08 02:35:52 (INFO):              RZR: 0
2016-09-08 02:35:52 (INFO):              SBD: 0
2016-09-08 02:35:52 (INFO):              SC: 0
2016-09-08 02:35:52 (INFO):              SDC: 0
2016-09-08 02:35:52 (INFO):              SHIBE: 0
2016-09-08 02:35:52 (INFO):              SHOPX: 0
2016-09-08 02:35:52 (INFO):              SILK: 0
2016-09-08 02:35:52 (INFO):              SJCX: 0
2016-09-08 02:35:52 (INFO):              SLR: 0
2016-09-08 02:35:52 (INFO):              SMC: 0
2016-09-08 02:35:52 (INFO):              SOC: 0
2016-09-08 02:35:52 (INFO):              SPA: 0
2016-09-08 02:35:52 (INFO):              SQL: 0
2016-09-08 02:35:52 (INFO):              SRCC: 0
2016-09-08 02:35:52 (INFO):              SRG: 0
2016-09-08 02:35:52 (INFO):              SSD: 0
2016-09-08 02:35:52 (INFO):              STEEM: 0
2016-09-08 02:35:52 (INFO):              STR: 0
2016-09-08 02:35:52 (INFO):              SUM: 0
2016-09-08 02:35:52 (INFO):              SUN: 0
2016-09-08 02:35:52 (INFO):              SWARM: 0
2016-09-08 02:35:52 (INFO):              SXC: 0
2016-09-08 02:35:52 (INFO):              SYNC: 0
2016-09-08 02:35:52 (INFO):              SYS: 0
2016-09-08 02:35:52 (INFO):              TAC: 0
2016-09-08 02:35:52 (INFO):              TOR: 0
2016-09-08 02:35:52 (INFO):              TRUST: 0
2016-09-08 02:35:52 (INFO):              TWE: 0
2016-09-08 02:35:52 (INFO):              UIS: 0
2016-09-08 02:35:52 (INFO):              ULTC: 0
2016-09-08 02:35:52 (INFO):              UNITY: 0
2016-09-08 02:35:52 (INFO):              URO: 0
2016-09-08 02:35:52 (INFO):              USDE: 0
2016-09-08 02:35:52 (INFO):              USDT: 0
2016-09-08 02:35:52 (INFO):              UTC: 0
2016-09-08 02:35:52 (INFO):              UTIL: 0
2016-09-08 02:35:52 (INFO):              UVC: 0
2016-09-08 02:35:52 (INFO):              VIA: 0
2016-09-08 02:35:52 (INFO):              VOOT: 0
2016-09-08 02:35:52 (INFO):              VOX: 0
2016-09-08 02:35:52 (INFO):              VRC: 0
2016-09-08 02:35:52 (INFO):              VTC: 0
2016-09-08 02:35:52 (INFO):              WC: 0
2016-09-08 02:35:52 (INFO):              WDC: 0
2016-09-08 02:35:52 (INFO):              WIKI: 0
2016-09-08 02:35:52 (INFO):              WOLF: 0
2016-09-08 02:35:52 (INFO):              X13: 0
2016-09-08 02:35:52 (INFO):              XAI: 0
2016-09-08 02:35:52 (INFO):              XAP: 0
2016-09-08 02:35:52 (INFO):              XBC: 0
2016-09-08 02:35:52 (INFO):              XC: 0
2016-09-08 02:35:52 (INFO):              XCH: 0
2016-09-08 02:35:52 (INFO):              XCN: 0
2016-09-08 02:35:52 (INFO):              XCP: 0
2016-09-08 02:35:52 (INFO):              XCR: 0
2016-09-08 02:35:52 (INFO):              XDN: 0
2016-09-08 02:35:52 (INFO):              XDP: 0
2016-09-08 02:35:52 (INFO):              XEM: 0
2016-09-08 02:35:52 (INFO):              XHC: 0
2016-09-08 02:35:52 (INFO):              XLB: 0
2016-09-08 02:35:52 (INFO):              XMG: 0
2016-09-08 02:35:52 (INFO):              XMR: 0
2016-09-08 02:35:52 (INFO):              XPB: 0
2016-09-08 02:35:52 (INFO):              XPM: 0
2016-09-08 02:35:52 (INFO):              XRP: 0
2016-09-08 02:35:52 (INFO):              XSI: 0
2016-09-08 02:35:52 (INFO):              XST: 0
2016-09-08 02:35:52 (INFO):              XSV: 0
2016-09-08 02:35:52 (INFO):              XUSD: 0
2016-09-08 02:35:52 (INFO):              XVC: 0
2016-09-08 02:35:52 (INFO):              XXC: 0
2016-09-08 02:35:52 (INFO):              YACC: 0
2016-09-08 02:35:52 (INFO):              YANG: 0
2016-09-08 02:35:52 (INFO):              YC: 0
2016-09-08 02:35:52 (INFO):              YIN: 0
2016-09-08 02:35:52 (INFO):     Setting up:
2016-09-08 02:35:52 (INFO):              Advice logger
2016-09-08 02:35:52 (INFO):
2016-09-08 02:35:52 (INFO):     Setting up:
2016-09-08 02:35:52 (INFO):              Profit Simulator
2016-09-08 02:35:52 (INFO):              Paper trader that logs fake profits.
2016-09-08 02:35:52 (INFO):

2016-09-08 02:35:52 (INFO):     Starting to watch the market: Poloniex /
2016-09-08 02:35:52 (DEBUG):    scheduling ticks
2016-09-08 02:35:52 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:35:53 (DEBUG):    Processing 200 new trades. From 2016-09-08 05:23:14 UTC to 2016-09-08 05:35:43 UTC. (12 minutes)
2016-09-08 02:36:12 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:36:13 (DEBUG):    Processing 9 new trades. From 2016-09-08 05:35:56 UTC to 2016-09-08 05:36:10 UTC. (a few seconds)
2016-09-08 02:36:32 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:36:33 (DEBUG):    No new trades.
2016-09-08 02:36:52 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:36:53 (DEBUG):    Processing 3 new trades. From 2016-09-08 05:36:32 UTC to 2016-09-08 05:36:46 UTC. (a few seconds)
2016-09-08 02:37:12 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:37:14 (DEBUG):    No new trades.
2016-09-08 02:37:32 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:37:34 (DEBUG):    Processing 3 new trades. From 2016-09-08 05:37:13 UTC to 2016-09-08 05:37:29 UTC. (a few seconds)
2016-09-08 02:37:52 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:37:53 (DEBUG):    Processing 9 new trades. From 2016-09-08 05:37:36 UTC to 2016-09-08 05:37:46 UTC. (a few seconds)
2016-09-08 02:38:12 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:38:14 (DEBUG):    Processing 1 new trades. From 2016-09-08 05:37:55 UTC to 2016-09-08 05:37:55 UTC. (a few seconds)
2016-09-08 02:38:32 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:38:34 (DEBUG):    Processing 4 new trades. From 2016-09-08 05:38:11 UTC to 2016-09-08 05:38:28 UTC. (a few seconds)
2016-09-08 02:38:52 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:38:54 (DEBUG):    Processing 1 new trades. From 2016-09-08 05:38:38 UTC to 2016-09-08 05:38:38 UTC. (a few seconds)
2016-09-08 02:39:12 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:39:13 (DEBUG):    Processing 2 new trades. From 2016-09-08 05:38:53 UTC to 2016-09-08 05:38:59 UTC. (a few seconds)
2016-09-08 02:39:32 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:40:52 (DEBUG):    Processing 22 new trades. From 2016-09-08 05:39:14 UTC to 2016-09-08 05:40:41 UTC. (a minute)
2016-09-08 02:41:07 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:41:09 (DEBUG):    Processing 7 new trades. From 2016-09-08 05:40:55 UTC to 2016-09-08 05:41:05 UTC. (a few seconds)
2016-09-08 02:41:27 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:41:29 (DEBUG):    Processing 5 new trades. From 2016-09-08 05:41:11 UTC to 2016-09-08 05:41:20 UTC. (a few seconds)
2016-09-08 02:41:47 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:41:49 (DEBUG):    Processing 11 new trades. From 2016-09-08 05:41:28 UTC to 2016-09-08 05:41:43 UTC. (a few seconds)
2016-09-08 02:42:07 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:42:08 (DEBUG):    Processing 36 new trades. From 2016-09-08 05:41:48 UTC to 2016-09-08 05:42:03 UTC. (a few seconds)
2016-09-08 02:42:27 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:42:29 (DEBUG):    Processing 7 new trades. From 2016-09-08 05:42:07 UTC to 2016-09-08 05:42:26 UTC. (a few seconds)
2016-09-08 02:42:47 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:42:49 (DEBUG):    Processing 3 new trades. From 2016-09-08 05:42:27 UTC to 2016-09-08 05:42:31 UTC. (a few seconds)
2016-09-08 02:43:07 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:43:09 (DEBUG):    Processing 4 new trades. From 2016-09-08 05:42:47 UTC to 2016-09-08 05:43:06 UTC. (a few seconds)
2016-09-08 02:43:27 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:43:29 (DEBUG):    Processing 79 new trades. From 2016-09-08 05:43:11 UTC to 2016-09-08 05:43:24 UTC. (a few seconds)
2016-09-08 02:43:47 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:43:49 (DEBUG):    Processing 10 new trades. From 2016-09-08 05:43:33 UTC to 2016-09-08 05:43:46 UTC. (a few seconds)
2016-09-08 02:44:07 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:44:09 (DEBUG):    Processing 24 new trades. From 2016-09-08 05:43:46 UTC to 2016-09-08 05:44:06 UTC. (a few seconds)
2016-09-08 02:44:27 (DEBUG):    Requested / trade data from Poloniex ...
2016-09-08 02:44:29 (DEBUG):    Processing 11 new trades. From 2016-09-08 05:44:08 UTC to 2016-09-08 05:44:25 UTC. (a few seconds)
```

**Comment by rafaelcmrj** [comment] 2016-09-12 04:00
same thing here

**Comment by askmike** [comment] 2016-09-20 15:26
It looks like Gekko has not given out any advice yet. What strategy are you using & are you sure the advice should have triggered yet?

**Comment by askmike** [comment] 2016-09-20 15:42
duplicate of #390.

**Closed as completed by askmike** 2016-09-20 15:42 UTC
