### ISSUE TITLE
This is Gekko crashed with the following error: { "__augmented": true }

### ISSUE THREAD

**Issue by ptdev** [askmike/gekko#2355] opened 2018-07-23 10:13 UTC
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Run a live tradebot on poloniex

**Expected result** (what you hoped would happen)
Bot trades without errors

**Actual result** (unexpected outcome)
Bot traded once and then error occurred

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Bot was run after git pull, so using latest dev version.
Console output:
```
  <-- POST /api/getCandles
  --> POST /api/getCandles 200 318ms 5.09kb
2018-07-23T09:41:29.620Z 'cancel' 'xxxxxxxxxx'
RECEIVED ERROR IN GEKKO INSTANCE 2018-07-23-09-09-tradebot-269734093885865
{ __augmented: true }
  <-- POST /api/getCandles
  --> POST /api/getCandles 200 317ms 6.12kb
```

The watcher and tradebot logs show no errors. Watcher kept on watching but tradebot stopped after the error.
Let me know if there's any more information I can supply

**Comment by askmike** [comment] 2018-07-23 11:13
Have you by any chance tried a bot via the CLI? Wondering what error will see there?

Also: Were you ever successfully able to run a poloniex bot on the UI? Did you change anything? etc.

**Comment by ptdev** [comment] 2018-07-23 11:20
Hi. Yes, I have been able to run a bot on poloniex from the GUI before on v5

But anyway, I've just stopped the GUI and started a tradebot from the command line with the same parameters. I'll keep you posted if it crashes or errors out again.

Thanks

**Comment by ptdev** [comment] 2018-07-23 14:40
Hey, updating this issue.
Gekko's been running the same strategy from the command line for some time now and no errors so far.
I think I'll just stick with running it like this from now on since I'll also be building and testing a custom plugin so I'll have to anyway.
I think you can close this issue if you don't need it anymore. Thanks

**Comment by askmike** [comment] 2018-07-23 15:05
I have honestly never seen this error before, and it's a bit hard to debug since I won't know how to reproduce this. I'll close this with cannot-reproduce tag. If someone else gets it we can reinvestigate.

**Closed as completed by askmike** 2018-07-23 15:05 UTC
Labels: cannot-reproduce

**Comment by askmike** [comment] 2018-07-24 08:09
Hmmm, more people. See #2357.
