### ISSUE TITLE
Question about multi-currencies on the same market/account

### ISSUE THREAD

**Issue by Yetzira** [askmike/gekko#1776] opened 2018-01-23 17:34 UTC
Hi
I'm sorry this is not a bug report nor a change request nor a question about decision in the repo.
But I couldn't register on the forum so I ask it here ... close the thread if useless !

I was wondering what's the best suggested way to go to trade LTC AND ETH at the same time on the same market (let's say kraken) ?
Right now i didn't want to take any risk so I just cloned the whole gekko directory to have one instance for eth and one for ltc; but I4m still using paper trader.

Now I want to try it "live". I'm wondering how it will deal with the amount of currency when it will start to trade both assets ?
Will it bae its buy/Sell on the amounts of assets/currencies it recalculates each time from the conf with fees, ot will it request the amounts on the market and trade as much currencies as it can whren it buys assets ?

Thanks all for your great work !

Yetz

**Comment by askmike** [comment] 2018-01-25 22:18
> But I couldn't register on the forum so I ask it here ... close the thread if useless !

Why not if I may ask? :)

> I was wondering what's the best suggested way to go to trade LTC AND ETH at the same time on the same market (let's say kraken) ?

Unfortunately this is not really supported. You can in theory start 3 Gekkos on different markets on the same account, however they will be battling for the same BTC (assuming your example were all BTC markets).

**Comment by askmike** [comment] 2018-01-25 22:18
Closing this as it's not a bug, but feel free to keep replying :)

**Closed as completed by askmike** 2018-01-25 22:18 UTC

**Comment by Yetzira** [comment] 2018-01-26 11:57
Hi
Actually forget my remark for the forum, I did receive the registration email to confirm the account, but it was tagged as spam by gmail ...

About the concurrent sessions on the same exchange, the only way to go for now would be either to find an exchanges which allows us to "partition" some pairs asset/currency so that they dont battle each other; or to use different accounts on the same exchanges, or different exchanges ?

Thanks
Yetz
