### ISSUE TITLE
"No new trades" keeps on coming when importing with no end time

### ISSUE THREAD

**Issue by pelletencate** [askmike/gekko#986] opened 2017-08-16 23:30 UTC
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
 - [x] bug report
 - [ ] feature request
 - [ ] question about the decisions made in the repository

* **Action taken** (what you did)

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//                       CONFIGURING IMPORTING
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* **Actions taken**

```
config.importer = {
  daterange: {
    // NOTE: these dates are in UTC
    from: "2017-08-14 17:00:00"
  }
}

$ node gekko -ic config.js
```

* **Expected result** (what you hoped would happen)
Imports and finishes

* **Actual result** (unexpected outcome)
It starts fine, but then at some point:
```
2017-08-16 23:23:49 (DEBUG):	Backwards: 2017-08-16T19:33:42.001Z (360265) to 2017-08-16T19:53:43.662Z (360364)
2017-08-16 23:23:49 (DEBUG):	Processing 100 new trades. From 2017-08-16 19:33:42 UTC to 2017-08-16 19:53:43 UTC. (20 minutes)
2017-08-16 23:23:50 (DEBUG):	Backwards: 2017-08-16T19:54:17.781Z (360365) to 2017-08-16T21:21:57.796Z (360464)
2017-08-16 23:23:50 (DEBUG):	Processing 100 new trades. From 2017-08-16 19:54:17 UTC to 2017-08-16 21:21:57 UTC. (an hour)
2017-08-16 23:23:50 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:50 (DEBUG):	Processing 100 new trades. From 2017-08-16 21:27:05 UTC to 2017-08-16 22:56:43 UTC. (2 hours)
2017-08-16 23:23:50 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:50 (DEBUG):	No new trades.
2017-08-16 23:23:50 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:50 (DEBUG):	No new trades.
2017-08-16 23:23:51 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:51 (DEBUG):	No new trades.
2017-08-16 23:23:51 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:51 (DEBUG):	No new trades.
2017-08-16 23:23:51 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:51 (DEBUG):	No new trades.
}
2017-08-16 23:23:51 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:51 (DEBUG):	No new trades.
2017-08-16 23:23:52 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:52 (DEBUG):	No new trades.
2017-08-16 23:23:52 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:52 (DEBUG):	No new trades.
2017-08-16 23:23:52 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:52 (DEBUG):	No new trades.
2017-08-16 23:23:52 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:52 (DEBUG):	No new trades.
2017-08-16 23:23:53 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:53 (DEBUG):	No new trades.
2017-08-16 23:23:53 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:53 (DEBUG):	No new trades.
2017-08-16 23:23:53 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:53 (DEBUG):	No new trades.
2017-08-16 23:23:53 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:53 (DEBUG):	No new trades.
2017-08-16 23:23:53 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:53 (DEBUG):	No new trades.
2017-08-16 23:23:54 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:54 (DEBUG):	No new trades.
2017-08-16 23:23:54 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:54 (DEBUG):	No new trades.
2017-08-16 23:23:54 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:54 (DEBUG):	No new trades.
2017-08-16 23:23:54 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:54 (DEBUG):	No new trades.
2017-08-16 23:23:54 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:54 (DEBUG):	No new trades.
2017-08-16 23:23:55 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:55 (DEBUG):	No new trades.
2017-08-16 23:23:55 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:55 (DEBUG):	No new trades.
2017-08-16 23:23:55 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:55 (DEBUG):	No new trades.
2017-08-16 23:23:55 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:55 (DEBUG):	No new trades.
2017-08-16 23:23:55 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:55 (DEBUG):	No new trades.
2017-08-16 23:23:56 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:56 (DEBUG):	No new trades.
2017-08-16 23:23:56 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:56 (DEBUG):	No new trades.
2017-08-16 23:23:56 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:56 (DEBUG):	No new trades.
2017-08-16 23:23:56 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:56 (DEBUG):	No new trades.
2017-08-16 23:23:56 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:56 (DEBUG):	No new trades.
2017-08-16 23:23:57 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:57 (DEBUG):	No new trades.
2017-08-16 23:23:57 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:57 (DEBUG):	No new trades.
2017-08-16 23:23:57 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:57 (DEBUG):	No new trades.
2017-08-16 23:23:57 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:57 (DEBUG):	No new trades.
2017-08-16 23:23:58 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:58 (DEBUG):	No new trades.
2017-08-16 23:23:58 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:58 (DEBUG):	No new trades.
2017-08-16 23:23:58 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:58 (DEBUG):	No new trades.
2017-08-16 23:23:58 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:58 (DEBUG):	No new trades.
2017-08-16 23:23:58 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:58 (DEBUG):	No new trades.
2017-08-16 23:23:59 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:59 (DEBUG):	No new trades.
2017-08-16 23:23:59 (DEBUG):	Backwards: 2017-08-16T21:27:05.907Z (360465) to 2017-08-16T22:56:43.618Z (360564)
2017-08-16 23:23:59 (DEBUG):	No new trades.
^C
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

What fixes it: Take the time that is mentioned (here: `17-08-16T21:27:05`), subtract one second, and assign it to `to:` in the daterange.

I tested this on GDAX.ETH_EUR. There's not a lot of activity on it, that may have to do with this.

**Comment by askmike** [comment] 2017-08-16 23:40
Dup of #952.

> What fixes it: Take the time that is mentioned (here: 17-08-16T21:27:05), subtract one second, and assign it to to: in the daterange.

So the issue is that in the importer we only check if the the importer is done after we check if there were no trades. I will discuss & fix in #952!

**Comment by askmike** [comment] 2017-08-17 00:12
It's actually a different bug!

**Comment by askmike** [comment] 2017-08-17 00:20
Fixed in develop!

**Comment by pelletencate** [comment] 2017-08-17 02:15
@askmike 

That doesn't seem to work. Before the fix, it ended here (see the dates!)
```
2017-08-17 02:14:17 (DEBUG):    Processing 100 new trades. From 2017-08-17 00:39:41 UTC to 2017-08-17 02:07:14 UTC. (an hour)
2017-08-17 02:14:18 (DEBUG):    Backwards: 2017-08-17T00:39:41.705Z (360618) to 2017-08-17T02:07:14.881Z (360717)
2017-08-17 02:14:18 (DEBUG):    No new trades.
```

After the fix, it ends half a day earlier.

```
2017-08-17 02:09:34 (DEBUG):    Backwards: 2017-08-16T14:06:29.73Z (358918) to 2017-08-16T14:09:26.982Z (359017)
2017-08-17 02:09:34 (DEBUG):    Processing 100 new trades. From 2017-08-16 14:06:29 UTC to 2017-08-16 14:09:26 UTC. (3 minutes)
2017-08-17 02:09:34 (DEBUG):    Backwards: 2017-08-16T14:09:26.982Z (359018) to 2017-08-16T14:09:26.982Z (359117)
2017-08-17 02:09:34 (DEBUG):    Processing 100 new trades. From 2017-08-16 14:09:26 UTC to 2017-08-16 14:09:26 UTC. (a few seconds)
2017-08-17 02:09:34 (INFO):     Done importing!
```

There are multiple batches of trades after this timestamp.

**Comment by askmike** [comment] 2017-08-17 09:30
Here are some notes:

- importing is always very exchange specific since each exchange API has a different way of offering historical trade data.
- GDAX importing was added by a contributor (I couldn't properly test at the time since GDAX was not available in my region/country).

The GDAX importer works like this:

1. Gekko requests data from time X (in the past)
2. Because you cannot query GDAX for trades happening on a date, but only on a trade ID. The GDAX module scans back in time to match trade ID with the desired start date.* (this is integrated using an API parameter not present in the GDAX API documentation).
3. After scanning back and having a tid the GDAX modules queries like so:
   - When Gekko needs new trades in importing mode:
   - GDAX give me 100 trades since last TID

However (based on your logs) it seems that if no trades happened since the last TID, GDAX will just return the same set. My bugfix was: if the same set was returned no new trades have happened (and thus we are done).

------

Questions:

> After the fix, it ends half a day earlier.

Can you check at the exchange if there were any trades after when Gekko ended?

Also: I cannot reproduce, can you post exactly what market, etc?

**Comment by pelletencate** [comment] 2017-08-17 21:52
I may be wrong here, but if the importer works the way I think I understand it works, your patch looks like it checks the time stamps of the trades. Now, here's the culprit: I downloaded a page of 100 trades that all happened in under a second. Your patch in https://github.com/askmike/gekko/commit/57c6a216c62bb009c72450d98f2ca6bccf354cdb thought because of that, that it ran into the last page. Instead, it should check the last trade ID.

**Comment by askmike** [comment] 2017-08-17 22:10
Ahhh yes I compared per second, though I have never seen that amounts of
trades on gdax.

**Closed as completed** 2017-08-18 19:35 UTC

**Comment by pelletencate** [comment] 2017-08-19 11:46
That doesn't help me though, I'll report a separate issue.
