### ISSUE TITLE
Few bugs + tips for getting running on Windows

### ISSUE THREAD

**Issue by cbp123** [askmike/gekko#890] opened 2017-07-28 08:29 UTC
Hi,
Just a few issues getting the last commit (53ffdf3) to run on Windows:

1) I had to add "ws" as a dependency in packages.json.

2) node-gyp requires Python 2, not 3 - I had to add a system Path variable pointing to a Python 2 installation instead.

3) For some reason, MSBuild was trying to find Microsoft.Cpp.Default.props in the root drive directory, rather than Program Files. I added an environment variable called VCTargetsPath pointing to C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\ and that fixed the issue.

All the best!

**Comment by thegamecat** [comment] 2017-07-28 09:05
I didn't manage to get talib working on Windows, did you manage that?

**Comment by askmike** [comment] 2017-07-28 09:07
I will try and see if I can reproduce that on windows.

> MSBuild was trying

Did you need MSBuild for compiling anything?

**Comment by deke997** [comment] 2017-08-15 02:50
@thegamecat I got talib working on Windows 10 [here](https://github.com/askmike/gekko/issues/732#issuecomment-322359189)

You can run gekko with TA-lib on Bash on Windows 10 (as long as you are running the 64 bit version of Windows 10). 
If you don't have Bash on Windows 10 yet, follow the instructions [here](https://www.windowscentral.com/how-install-bash-shell-command-line-windows-10)

Step 1: Open up bash and install node.js: (taken from [here](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions))

```
sudo apt-get update
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential
```

Step 2: Install Git

`sudo apt-get install git`

Step 3: Download and install gekko: (taken from [here](https://gekko.wizb.it/docs/installation/installing_gekko.html)):

```
git clone git://github.com/askmike/gekko.git
cd gekko
npm install --only=production
```

Step 4: Edit the handle.js file (taken from [here](https://github.com/askmike/gekko/issues/708#issuecomment-296329300))

Navigate to gekko/plugins/sqlite:

`cd  ~/gekko/plugins/sqlite`

Change line 53 in handle.js from 

`db.run("PRAGMA journal_mode = WAL"); `

to 

`db.run("PRAGMA journal_mode = DEL"); `

(I use nano for this --> `nano handle.js`)

Step 5: navigate back to /gekko and make sure you have the correct version of talib (taken from [here](https://github.com/askmike/gekko/issues/908#issuecomment-319657408))

```
cd ~/gekko
npm remove talib
npm install talib@1.0.2
```

Step 6: Start gekko:

`node gekko --ui`

Everything should work then!

**Comment by deke997** [comment] 2017-08-16 00:48
Also, when I was trying to get gekko running on Windows outside of Bash, I kept running into an error like [this one](https://github.com/karma-runner/grunt-karma/issues/157#issuecomment-138964789)

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not fi
nd WindowsSDKDir variable from the registry. TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. 
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. 
gyp ERR! build error
gyp ERR! stack Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack at ChildProcess.emit (events.js:110:17)
gyp ERR! stack at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
```

After hours of searching, I found out that even though I had VS 2015 installed, the needed dependencies are not installed until you actually _create_ a C++ project (see [here](https://stackoverflow.com/questions/33716369/error-trk0005-failed-to-locate-cl-exe/33716573#33716573)). So, once I opened VS 2015 and created a C++ project, it prompted me to install the needed dependencies, and then everything worked great.

This should probably be added to the docs as an issue that may be faced when installing on windows. Although, if you install through Bash (which I would recommend doing), obviously this will not matter.

**Comment by askmike** [comment] 2017-08-16 10:03
At exactly what command did you see that that message? I am assuming at `npm install`. So the idea is that if you have the LTS node version you don't need to compile (and thus not need `C:\Program Files (x86)\MSBuild`) because of `node-pre-gyp`.

**Comment by askmike** [comment] 2017-08-18 21:10
Closing this as unable to reproduce. If new people have problems, please open a new issue!

**Closed as completed by askmike** 2017-08-18 21:10 UTC
Labels: waiting-for-answer
