### ISSUE TITLE
GDAX Import keeps erroring out

### ISSUE THREAD

**Issue by klaypigeon** [askmike/gekko#1325] opened 2017-11-16 02:28 UTC
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Running import of 6 week timespan

* **Expected result** (what you hoped would happen)
data import

* **Actual result** (unexpected outcome)
Partial data import. Child process dies. Ubuntu Linux 16.04-64bit. Insured system is not going to sleep. Console output:

> <-- POST /api/scansets
>   --> POST /api/scansets 200 831ms 124b
> /opt/gekko/exchanges/gdax.js:262
>                 log.debug('Backwards: ' + last.time + ' (' + last.trade_id + ') to ' + first.time + ' (' + first.trade_id + ')');
>                                                ^
> 
> TypeError: Cannot read property 'time' of undefined
>     at Trader.<anonymous> (/opt/gekko/exchanges/gdax.js:262:48)
>     at Request._callback (/opt/gekko/node_modules/gdax/lib/clients/public.js:45:7)
>     at Request.self.callback (/opt/gekko/node_modules/gdax/node_modules/request/request.js:187:22)
>     at Request.emit (events.js:159:13)
>     at Request.<anonymous> (/opt/gekko/node_modules/gdax/node_modules/request/request.js:1044:10)
>     at Request.emit (events.js:159:13)
>     at IncomingMessage.<anonymous> (/opt/gekko/node_modules/gdax/node_modules/request/request.js:965:12)
>     at IncomingMessage.emit (events.js:164:20)
>     at endReadableNT (_stream_readable.js:1054:12)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
> RECEIVED ERROR IN IMPORT 290458505747063
> Child process has died.

* **Other information**
I have tried this numerous times and it continues to fail.

**Comment by tomand285** [comment] 2017-11-16 03:50
I have had this problem too on Ubuntu 17.10. I was importing GDAX and found out that this problem can be caused by 2 things. 

1. The exchange did not have the data because it does not exist at the range you are asking for.
2. Some other reason that I do not know yet but think it could be due to either sending too many requests to the server or some glitch in the system either on your end or the exchange's. 

If I get time or if someone else can, add a debug line to see what gekko is receiving for import and wait for the import to fail. We can then further debug the problem or at least know more about the source of the error.

**Comment by CMyers79** [comment] 2017-11-30 15:50
This also occurs on Windows 10, sometimes immediately, sometimes after a few days of data has been imported.  It used to work perfectly, so I suspect the issue is on GDAX's end, possibly due to high server demand.

**Comment by askmike** [comment] 2017-12-11 06:35
should be fixed now :)

**Closed as completed by askmike** 2017-12-11 06:35 UTC
