### ISSUE TITLE
Wrong Last buy price

### ISSUE THREAD

**Issue by alexandershalin** [askmike/gekko#2484] opened 2018-08-28 11:16 UTC
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Tradebot started

**Expected result** (what you hoped would happen)
Last buy price should be equal to the price of order when it is filled.

**Actual result** (unexpected outcome)
Seems that Last buy price is equal to the price when order was placed and was not fully filled.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Do not know if it is strat (NN2) dependent.
[2018-08-28-09-22-tradebot-433850886225034.log](https://github.com/askmike/gekko/files/2327743/2018-08-28-09-22-tradebot-433850886225034.log)

```
2018-08-28 10:22:04 (INFO):	[ORDER] partial buy fill, total filled: 12.87
2018-08-28 10:22:04 (DEBUG):	[ORDER] statusChange: FILLED
2018-08-28 10:22:06 (INFO):	[ORDER] summary: { price: 0.016426,
  amount: 12.87,
  date: moment("2018-08-28T10:22:04.161"),
  side: 'buy',
  orders: 1,
  fees: { BNB: 0.00407815 },
  feePercent: 0.07500000000000001 }
2018-08-28 10:22:06 (DEBUG):	syncing private data
2018-08-28 10:22:35 (DEBUG):	
      Current market: bear
      Percent change predicted: -0.009370962532427684
      Current price: 0.016426
      Last buy price: 0.01635
      Current position: long
```

**Comment by askmike** [comment] 2018-08-28 12:07
`Last buy price` is not from Gekko, but from the strategy (which is logging it's own variable). That's where the bug is! Closing this as it's not a bug within Gekko.

Feel free to keep on commenting, but we need to look at the strategy if we want to fix this, so maybe link that as well!

**Closed as completed by askmike** 2018-08-28 12:07 UTC
