### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by zhaoxiaohui** [askmike/gekko#1090] opened 2017-09-07 09:31 UTC
for live Gekkos, after starting the runner, got the wrong message from console

Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at Oe.e.$emit (build.js:6)
    at a.s.onmessage (build.js:6)
    at HTMLDivElement.<anonymous> (reconnecting-websocket.min.js:2)
    at WebSocket.h.onmessage (reconnecting-websocket.min.js:2)

**Comment by oktapodia** [comment] 2017-09-08 00:57
Which strategy? Configuration?

**Comment by pavel-main** [comment] 2017-09-09 02:21
Same problem. Using DEMA strategy with default parameters, 1 minute candle size and 1 minute warmup period.

**Comment by askmike** [comment] 2017-09-09 10:35
These look like browser console logs. Is anything else broke on the page? And do you know what button / page triggered triggered them?

**Comment by markanderson** [comment] 2017-09-10 14:54
This happened to me last night after pulling in the latest stable changes. I noticed that my config file was using the old syntax (paper trader variables were different) which triggered this same error. If you start from the latest sample-config.json, this might go away.

**Comment by askmike** [comment] 2017-09-15 15:17
@markanderson yes this is definitely a problem (people have to make sure the config is up to date). Though I doubt this is the same as OP, since I think those are logs from the UI (which builds a config dynamically and does not use a `config.js` file.

Closing this as unable to reproduce, if anyone has more information on this let me know :)

**Closed as completed by askmike** 2017-09-15 15:17 UTC
Labels: waiting-for-answer
