### ISSUE TITLE
Setting Trading Amount / Percentage

### ISSUE THREAD

**Issue by Misanthrop87** [askmike/gekko#491] opened 2016-11-01 18:42 UTC
Hey,

is there any possibility to set a maximum amount of how much money shall be set per bid? Or a percentage of the existing money? I cannot find it in the configuration... and I dont find a documentation of it. Or is it maybe the "currency" in the profit simulator?

Kind regards
David

**Comment by Pascal66** [comment] 2016-11-01 20:43
see #450

**Comment by askmike** [comment] 2016-11-01 20:44
Will merge that in tonight!

**Comment by greenbigfrog** [comment] 2017-12-14 10:17
Duplicate of #937 . @askmike this issue should be closed

**Closed as completed** 2017-12-14 17:29 UTC
