### ISSUE TITLE
No trades made in binance(part 2)

### ISSUE THREAD

**Issue by Daakko** [askmike/gekko#1851] opened 2018-02-03 19:27 UTC
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
After the advice of askmike in #1849 ive set the historical candles to 1.  ive expected at least one trade

* **Expected result** (what you hoped would happen)
did try to make an trade(sell wing-eth)

* **Actual result** (unexpected outcome)
trade was canceld. A error occured(check below)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I am in possesion of 154x wing. 

Check below the error

C:\gekko\gekko-develop\exchanges\binance.js:304
      if(_.get(data, 'msg') === 'UNKNOWN_ORDER') {  // this seems to be the response we get when an order was filled
           ^

TypeError: _.get is not a function
    at Trader.cancel (C:\gekko\gekko-develop\exchanges\binance.js:304:12)
    at bound (C:\gekko\gekko-develop\node_modules\lodash\dist\lodash.js:729:21)
    at C:\gekko\gekko-develop\core\util.js:28:7
    at C:\gekko\gekko-develop\exchanges\binance.js:75:12
    at Request.request [as _callback] (C:\gekko\gekko-develop\node_modules\binance\lib\rest.js:90:25)
    at Request.self.callback (C:\gekko\gekko-develop\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\gekko\gekko-develop\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
RECEIVED ERROR IN GEKKO 758986165014771
Child process has died.

What did i do wrong?
[2018-02-03-08-19-UTC-watcher.log](https://github.com/askmike/gekko/files/1692101/2018-02-03-08-19-UTC-watcher.log)
[2018-02-03-08-19-UTC-tradebot.log](https://github.com/askmike/gekko/files/1692102/2018-02-03-08-19-UTC-tradebot.log)

**Comment by Daakko** [comment] 2018-02-03 23:35
So i found the fault. I sld my Wings and started trading ETH-FUEL. After the history files were done ive got 2 attempts of buying fuel 1 confirmed buy of Fuel and 2 attempts of selling Fuel and the third attempt was a confirmed sell. After that this error come in

C:\gekko\gekko-develop\plugins\performanceAnalyzer\performanceAnalyzer.js:112
    duration: this.roundTrip.exit.date.diff(this.roundTrip.entry.date)
                                       ^

TypeError: this.roundTrip.exit.date.diff is not a function
    at PerformanceAnalyzer.handleRoundtrip (C:\gekko\gekko-develop\plugins\performanceAnalyzer\performanceAnalyzer.js:112:40)
    at PerformanceAnalyzer.bound [as handleRoundtrip] (C:\gekko\gekko-develop\node_modules\lodash\dist\lodash.js:729:21)
    at PerformanceAnalyzer.logRoundtripPart (C:\gekko\gekko-develop\plugins\performanceAnalyzer\performanceAnalyzer.js:94:10)
    at PerformanceAnalyzer.bound [as logRoundtripPart] (C:\gekko\gekko-develop\node_modules\lodash\dist\lodash.js:729:21)
    at PerformanceAnalyzer.processTrade (C:\gekko\gekko-develop\plugins\performanceAnalyzer\performanceAnalyzer.js:72:8)
    at Trader.bound (C:\gekko\gekko-develop\node_modules\lodash\dist\lodash.js:729:21)
    at emitOne (events.js:121:20)
    at Trader.emit (events.js:211:7)
    at Trader.bound [as emit] (C:\gekko\gekko-develop\node_modules\lodash\dist\lodash.js:729:21)
    at Manager.Trader.manager.on.trade (C:\gekko\gekko-develop\plugins\trader\trader.js:24:10)
RECEIVED ERROR IN GEKKO 818373979587152
Child process has died.

So whats wrong. 
[2018-02-03-20-47-UTC-tradebot.log](https://github.com/askmike/gekko/files/1692297/2018-02-03-20-47-UTC-tradebot.log)
[2018-02-03-20-47-UTC-watcher.log](https://github.com/askmike/gekko/files/1692298/2018-02-03-20-47-UTC-watcher.log)

**Comment by rkingy** [comment] 2018-02-04 20:04
@Daakko I've got this issue too.. can try debug it tonight.. seems to be caused by some updates on the develop branch.. Are you able to label this issue as a bug?

**Comment by Daakko** [comment] 2018-02-04 20:25
I have no idea how to do that. If you tell me ill issue the label

**Comment by rkingy** [comment] 2018-02-04 20:39
@askmike Are you able to mark this issue as a bug? I'll try and look at this tonight after work. Seems to be related to some of the recent commits on develop branch. I was running fine until last night when I downloaded the latest (1 week) develop branch updates and now hitting this issue.

**Comment by askmike** [comment] 2018-02-05 03:08
What version of Gekko did you guys install? stable release or develop branch?

**Comment by rkingy** [comment] 2018-02-05 04:06
@askmike Latest version of develop branch.
Up to the 4th Feb 2018 "Fix Dema (#1822)" commit

I think the issue is that binance is completely broken on the Stable branch right now.. unless all the updates for minimum orders values can be hot fixed to stable. This is the main issue for me not using Stable right now.

I'm currently running my own branch with cherry picked commits to make things work :)

**Comment by Daakko** [comment] 2018-02-05 04:24
i use develop. I couldnt find stable. But if i believe @rkingy both aint working

**Comment by askmike** [comment] 2018-02-05 04:56
> I think the issue is that binance is completely broken on the Stable branch right now.. unless all the updates for minimum orders values can be hot fixed to stable.

I am trading fine on binance (latest stable release) and have been for a week now, it hasn't crashed for over a week. So I guess it depends on what markets you are trading on?

> unless all the updates for minimum orders values can be hot fixed to stable.

I guess this has to do with how much money you have on the exchange, or not? I'll come out with a new release asap, binance is a one of the most used exchanges.

**Comment by askmike** [comment] 2018-02-05 04:58
just to be sure we are all on the same line:

> TypeError: _.get is not a function

This error has been fixed in latest develop. So I guess you guys are now both talking about this one?

> TypeError: this.roundTrip.exit.date.diff is not a function

**Comment by rkingy** [comment] 2018-02-05 05:17
Correct the line in question is 
`TypeError: this.roundTrip.exit.date.diff is not a function`

It appears that the exit.date is not a moment object..

**Comment by askmike** [comment] 2018-02-05 05:19
I'll look at it asap, for now I am closing this issue as a dup of #1862.

@rkingy this error has happened before, it has to do with some events from other plugins not being propagated in the right order.

**Closed as completed by askmike** 2018-02-05 05:19 UTC
Labels: bug

**Comment by rkingy** [comment] 2018-02-05 05:36
Roger that, thanks!, If that leads to a dead end, where I was looking was /exchanges/binance.js on line 89 we have the following 

`date: moment(trade.timestamp).unix()`

I'm wondering if this .timestamp is in the correct 13 digit millisecond type.. if it's a 13 digit one we need to just go moment(trade.timestamp) without the .unix() part on the end. If its a seconds version (10 digit) we need to go moment.unix(1318781876);

But doesn't really explain why this seems to be intermittent.. so probably looking in the wrong place.

**Comment by askmike** [comment] 2018-02-05 05:49
The unix part doesn't change how moment parses the timestamp, it just converts it into date that defaults to UTC timezone.
