### ISSUE TITLE
'npm install --only=production' failure

### ISSUE THREAD

**Issue by camarigor** [askmike/gekko#2205] opened 2018-05-25 02:31 UTC
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
npm install --only=production

**Expected result** (what you hoped would happen)
Installation complete.

**Actual result** (unexpected outcome)

12659 verbose stack Error: sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
12659 verbose stack Exit status 1
12659 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
12659 verbose stack     at EventEmitter.emit (events.js:182:13)
12659 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
12659 verbose stack     at ChildProcess.emit (events.js:182:13)
12659 verbose stack     at maybeClose (internal/child_process.js:957:16)
12659 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
12660 verbose pkgid sqlite3@3.1.13
12661 verbose cwd /home/goat/git/gekko
12662 verbose Linux 4.16.6-1-ARCH
12663 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--only=production"
12664 verbose node v10.1.0
12665 verbose npm  v6.0.1
12666 error code ELIFECYCLE
12667 error errno 1
12668 error sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
12668 error Exit status 1
12669 error Failed at the sqlite3@3.1.13 install script.
12669 error This is probably not a problem with npm. There is likely additional logging output above.
12670 verbose exit [ 1, true ]

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment] 2018-05-25 10:48
Please try again with the LTS version of nodejs. If that doesn't work please ask around on the forum or on discord, see here: https://gekko.wizb.it/docs/introduction/getting_help.html

This is definitely an installation issue with a dependency (sqlite) and not a bug in Gekko, so unfortunately I am closing this :(

**Closed as completed by askmike** 2018-05-25 10:48 UTC
