### ISSUE TITLE
Unsupported exchange: okcoin.cn 

### ISSUE THREAD

**Issue by codewithyou** [askmike/gekko#913] opened 2017-08-02 23:45 UTC
Unsupported exchange: okcoin.cn 

how to support it ?

**Comment by codewithyou** [comment] 2017-08-02 23:50
config.watch = {

  // see https://gekko.wizb.it/docs/introduction/supported_exchanges.html
  exchange: 'Okcoin.cn',
  currency: 'CNY',
  asset: 'BTC',
    tickrate: 8
  // You can set your own tickrate (refresh rate).
  // If you don't set it, the defaults are 2 sec for
  // okcoin and 20 sec for all other exchanges.
  // tickrate: 20
}

**Comment by askmike** [comment] 2017-08-03 09:55
duplicate of #912.

**Closed as completed by askmike** 2017-08-03 09:55 UTC
