### ISSUE TITLE
Gekko missing trades

### ISSUE THREAD

**Issue by whoodat** [askmike/gekko#2226] opened 2018-06-05 17:53 UTC
Gekko is consistently missing trades, is there a way to trace where it is dropping. Whether it is missing trades because the gekko connection is timing out or whether its because the connection on the coinbase side is messing up?

It returns this error a lot:
 2018-06-05 10:34:14 (ERROR):       [gdax.js] (getOrder) returned an irrecoverable error: NotFound

**Comment by askmike** [comment] 2018-07-04 15:02
Why do you think it was missing trades? That error means there was a problem connecting to GDAX, but Gekko will try to reconnect again. Regardless: GDAX integration has been greatly improved in 0.6, please download that version and try again.

**Comment by 3pm** [comment] 2018-07-11 11:45
I can confirm the issue.  But cannot tell exact situation when it happens.
I managed to compare live candle import results vs post live import results (with -import switch) for USDBTC from bitfinex.com into PostgreSQL database. In greater period there are always differences in count of trades etc.  in some particular records. Sometimes missing trades goes to next time hop, sometimes they are missing at all. But can be bitfinex's fault as well.

**Comment by nervousfinger** [comment] 2018-08-20 06:30
I also can confirm the issue on bitfinex.
Gekko is placing an order, does some [ORDER] statusChange: MOVING and [ORDER] statusChange: OPEN for a few minutes. It then stops moving the order even if it is not filled and does not catch the order filled signal later on, resulting in not being able to execute the next order because it still thinks it's selling or buying.

[EDIT]
forgot to mention: noticed this in latest stable and in development branch pulled yesterday.

**Comment by askmike** [comment] 2018-08-20 07:10
Can everyone who still experiences this run the branch found in #2463 (see instructions there).

**Comment by askmike** [comment] 2018-09-30 18:33
I am assuming this is now fixed.

**Closed as completed by askmike** 2018-09-30 18:33 UTC
Labels: waiting-for-answer
