### ISSUE TITLE
Roundtrips inaccuracy

### ISSUE THREAD

**Issue by generalectric** [askmike/gekko#1254] opened 2017-10-28 02:15 UTC
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

    Running an import and then backtesting to see some results the round trips seem to drift a tad and differ from backtest to backtest

* **Expected result** (what you hoped would happen)

    Roundtrips should be the same

* **Actual result** (unexpected outcome)

    Roundtrips differ from backtest to backtest during an import

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment] 2017-10-28 02:23
I am pretty sure it has to do with what timezone times we are displaying, see #895. Is this what you mean?

**Comment by generalectric** [comment] 2017-10-28 02:48
Im not too sure... but no... i dont believe so??

https://gist.github.com/generalectric/e10037a35e129514c484bdaeb01619e3

In that gist is 2 roundtrip reports well a large section of them. Put them in notepad side by side and compare them. they were ran a couple minutes apart

**Comment by askmike** [comment] 2017-10-28 02:52
ah okay, can you tell me a little bit about your strategy?

**Comment by generalectric** [comment] 2017-10-28 03:18
im thinking the problem is that its using linear regression

**Comment by generalectric** [comment] 2017-10-28 03:58
think i found part of the problem

    this.decision = '';
      if (indicator > settings.up)
        this.decision = 'short';
      else if (indicator < settings.down)
        this.decision = 'long';

    this.advice(this.decision);

by removing this.decision and replacing with this.advice('long') or short hardcoded i have successfully wiped out half my profit. I was thinking those numbers were a little too good
   
going to do another import and retest

**Comment by askmike** [comment] 2017-10-28 04:09
Are you running normal gekko or your own version (in the PR)? Your PR
removed the exact safety check that should prevent these mistakes from
effecting results.

**Comment by generalectric** [comment] 2017-10-28 04:26
oh man thats pure gold! lol ok so i have original code back in place. im still showing rountrips changing on every back test during an import though. going to run another strat on it....

**Comment by generalectric** [comment] 2017-10-28 04:32
ok so running base native MACD strategy im having same results. i am currently importing a year of data for eth using postgresql plugin. going to do fresh clone and retest

**Comment by generalectric** [comment] 2017-10-28 04:59
yeah confirmed.... fresh clone using native macd strat with 5 minute candles on any market. backtesting during an import using pgsql SOME of the roundtrips are different from backtest to backtest

**Comment by askmike** [comment] 2017-10-28 05:38
Can you give me an exact timeframe + market + indicator settings? Else I
cannot reproduce.

On 28 Oct 2017 11:59, "generalectric" <notifications@github.com> wrote:

yeah confirmed.... fresh clone using native macd strat with 5 minute
candles on any market. backtesting during an import using pgsql SOME of the
roundtrips are different from backtest to backtest

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/askmike/gekko/issues/1254#issuecomment-340139609>, or mute
the thread

**Comment by generalectric** [comment] 2017-10-28 06:00
poloniex eth_btc
candleSize: 5,
historySize: 274,
method: 'MACD',
  thresholds: {
    down: -0.0001,
    up: 0.0001,
  }

do an import using pgsql from 2017-01-01 00:00:00
while importing run multiple backtests and compare the last few lines of each roundtrip report

**Comment by generalectric** [comment] 2017-10-28 17:21
gave it another test on a different market... same. i just wanted to make sure i wasnt sending you on a wild goose chase. you have to really look for it and its not the easiest. and it will take you several runs to find it. but write down all the numbers forget hours or minutes just write down a list of the numbers for time for a couple days on a roundtrip report... then retest... look at the same dates on the new run.. and compare the numbers.... they change

if a backtest has already been run... regardless of if its still importing... how does the current roundtrip effect what the time range was for a roundtrip 2 days ago. that means the current round trip is rewriting or altering history, which shouldnt be possible

**Comment by mattgauzza** [comment] 2017-11-01 21:04
Round trip discrepancies are happening for me as well on both windows and linux machines
https://www.screencast.com/t/526ss0GjyRt
that is just default MACD with some polinex data pulled in.  Same issue happens in gdax.  Sometimes the buys and sells aren't even for the correct amount that was output in the console.
https://www.screencast.com/t/wUgBXYcRXSAs
in the console the first 
long is for 297.22
and the next short is 295.58
the graph is right and the console is right but the round trips are wrong and the calculations are wrong

**Comment by mattgauzza** [comment] 2017-11-02 02:05
Hey @askmike  I found the issue with the pricing not matching up
https://github.com/askmike/gekko/blob/stable/plugins/performanceAnalyzer/performanceAnalyzer.js#L84
Change this function logRoundtripPart to use  trade.price and trade.portfolio.currency instead of this.price and this.current etc see below:
https://github.com/gauzzastrip/gekko/blob/stable/plugins/performanceAnalyzer/performanceAnalyzer.js#L82

**Comment by mattgauzza** [comment] 2017-11-02 02:50
https://github.com/askmike/gekko/pull/1282

**Comment by askmike** [comment] 2017-11-02 03:26
Thanks @gauzzastrip your PR has been merged into develop. @generalectric can you check the develop branch to see if it fixes your problem?

**Comment by generalectric** [comment] 2017-11-04 01:38
The following happens while importing data and using scan to automatically get the dateranges. Running stock MACD strat then waiting a few minutes to re test you can see that the exposed duration changes from backtest to backtest. This is on every market. After @gauzzastrip's commit I'm still having the same results. Nice find though @gauzzastrip! I think issue title maybe better suited as Roundtrips exposed duration inaccuracy.

*edit*
Then again after another look i think the title is fine... maybe roundtrips inaccurate while importing... but this bug makes me question the accuracy of roundtrips altogether.

    2017-11-03 20:07:41 (INFO):     (ROUNDTRIP) REPORT:
    2017-11-03 20:07:41 (INFO):     (ROUNDTRIP) entry date (UTC)    exit date (UTC)         exposed duration        P&L     profit
    2017-11-03 20:07:41 (INFO):     (ROUNDTRIP) 2017-01-03 02:00    2017-01-07 23:30        5 days                  -108.25 -11.24
    2017-11-03 20:07:41 (INFO):     (ROUNDTRIP) 2017-01-11 11:00    2017-01-12 19:30        a day                   -14.12  -1.65
    2017-11-03 20:07:41 (INFO):     (ROUNDTRIP) 2017-01-17 00:00    2017-01-26 09:00        9 days                  71.06   8.48
    2017-11-03 20:07:41 (INFO):     (ROUNDTRIP) 2017-01-29 15:00    2017-02-10 21:00        12 days                 82.46   9.09
    2017-11-03 20:07:41 (INFO):     (ROUNDTRIP) 2017-02-15 06:30    2017-03-09 15:00        22 days                 174.40  17.67
    2017-11-03 20:07:41 (INFO):     (ROUNDTRIP) 2017-03-15 11:00    2017-03-19 12:00        4 days                  -231.24 -19.95
    2017-11-03 20:07:41 (INFO):     (ROUNDTRIP) 2017-03-22 13:30    2017-03-23 11:00        a day                   29.33   3.17
    2017-11-03 20:07:41 (INFO):     (ROUNDTRIP) 2017-03-23 11:30    2017-03-25 21:00        2 days                  -74.08  -7.77
    2017-11-03 20:07:41 (INFO):     (ROUNDTRIP) 2017-03-29 17:30    2017-04-14 22:30        16 days                 150.19  17.11
    2017-11-03 20:07:41 (INFO):     (ROUNDTRIP) 2017-04-19 10:00    2017-05-15 21:00        a month                 426.11  41.53
    2017-11-03 20:07:41 (INFO):     (ROUNDTRIP) 2017-05-20 10:30    2017-05-20 17:30        7 hours                 33.87   2.34
    2017-11-03 20:07:41 (INFO):     (ROUNDTRIP) 2017-05-21 12:00    2017-05-28 23:30        8 days                  -5.04   -0.34
    2017-11-03 20:07:41 (INFO):     (ROUNDTRIP) 2017-06-01 16:30    2017-06-01 20:00        4 hours                 39.44   2.68

-------------------------------------------------------------------------------------------------------------

    2017-11-03 20:20:16 (INFO):     (ROUNDTRIP) REPORT:
    2017-11-03 20:20:16 (INFO):     (ROUNDTRIP) entry date (UTC)    exit date (UTC)         exposed duration        P&L     profit
    2017-11-03 20:20:16 (INFO):     (ROUNDTRIP) 2017-01-02 22:39    2017-01-07 23:39        5 days                  -106.09 -11.03
    2017-11-03 20:20:16 (INFO):     (ROUNDTRIP) 2017-01-16 23:39    2017-01-26 09:09        9 days                  74.21   8.69
    2017-11-03 20:20:16 (INFO):     (ROUNDTRIP) 2017-01-29 14:09    2017-02-11 04:09        13 days                 80.45   8.69
    2017-11-03 20:20:16 (INFO):     (ROUNDTRIP) 2017-02-15 06:39    2017-03-09 15:09        22 days                 176.57  17.58
    2017-11-03 20:20:16 (INFO):     (ROUNDTRIP) 2017-03-15 13:09    2017-03-19 12:09        4 days                  -234.22 -19.87
    2017-11-03 20:20:16 (INFO):     (ROUNDTRIP) 2017-03-22 13:39    2017-03-23 10:39        21 hours                22.04   2.34
    2017-11-03 20:20:16 (INFO):     (ROUNDTRIP) 2017-03-23 12:09    2017-03-25 20:39        2 days                  -83.24  -8.64
    2017-11-03 20:20:16 (INFO):     (ROUNDTRIP) 2017-03-29 17:39    2017-04-14 22:09        16 days                 145.22  16.54
    2017-11-03 20:20:16 (INFO):     (ROUNDTRIP) 2017-04-19 09:39    2017-05-15 21:39        a month                 418.80  41.02
    2017-11-03 20:20:16 (INFO):     (ROUNDTRIP) 2017-05-20 10:09    2017-05-20 17:39        8 hours                 30.43   2.12
    2017-11-03 20:20:16 (INFO):     (ROUNDTRIP) 2017-05-21 12:09    2017-05-22 04:09        16 hours                27.59   1.88
    2017-11-03 20:20:16 (INFO):     (ROUNDTRIP) 2017-05-22 09:09    2017-05-28 23:39        7 days                  -21.50  -1.44
    2017-11-03 20:20:16 (INFO):     (ROUNDTRIP) 2017-06-01 16:09    2017-06-01 20:39        5 hours                 36.13   2.47
    2017-11-03 20:20:16 (INFO):     (ROUNDTRIP) 2017-06-01 21:39    2017-06-14 11:09        13 days                 233.89  15.62

**Comment by generalectric** [comment] 2017-11-04 02:04
Apparently the problem appears to be the exit dates are changing from backtest to backtest. If you'll notice 2017-01-12 19:30 (the second entry) is missing in the second backtest. Here is the corresponding buy/sells for the above backtests... the first backtest then the second backtest same as above.

    2017-11-03 20:07:26 (INFO):     2017-01-01 00:00:00: Paper trader simulated a SELL      965.21769780 USDT <= 0.00000000 BTC
    2017-11-03 20:07:26 (INFO):     2017-01-02 20:00:00: Paper trader simulated a BUY       0.00000000 USDT => 0.94439927 BTC
    2017-11-03 20:07:26 (INFO):     2017-01-07 17:30:00: Paper trader simulated a SELL      855.03652620 USDT <= 0.00000000 BTC
    2017-11-03 20:07:27 (INFO):     2017-01-11 05:00:00: Paper trader simulated a BUY       0.00000000 USDT => 1.02673106 BTC
    2017-11-03 20:07:27 (INFO):     2017-01-12 13:30:00: Paper trader simulated a SELL      839.21095267 USDT <= 0.00000000 BTC
    2017-11-03 20:07:27 (INFO):     2017-01-16 18:00:00: Paper trader simulated a BUY       0.00000000 USDT => 1.00984940 BTC
    2017-11-03 20:07:28 (INFO):     2017-01-26 03:00:00: Paper trader simulated a SELL      908.58871052 USDT <= 0.00000000 BTC
    2017-11-03 20:07:29 (INFO):     2017-01-29 09:00:00: Paper trader simulated a BUY       0.00000000 USDT => 0.98687628 BTC
    2017-11-03 20:07:30 (INFO):     2017-02-10 15:00:00: Paper trader simulated a SELL      989.23609856 USDT <= 0.00000000 BTC
    2017-11-03 20:07:30 (INFO):     2017-02-15 00:30:00: Paper trader simulated a BUY       0.00000000 USDT => 0.98226998 BTC
    2017-11-03 20:07:32 (INFO):     2017-03-09 09:00:00: Paper trader simulated a SELL      1161.66193773 USDT <= 0.00000000 BTC
    2017-11-03 20:07:33 (INFO):     2017-03-15 06:00:00: Paper trader simulated a BUY       0.00000000 USDT => 0.93088911 BTC
    2017-11-03 20:07:33 (INFO):     2017-03-19 07:00:00: Paper trader simulated a SELL      928.09830458 USDT <= 0.00000000 BTC
    2017-11-03 20:07:34 (INFO):     2017-03-22 08:30:00: Paper trader simulated a BUY       0.00000000 USDT => 0.90808049 BTC
    2017-11-03 20:07:34 (INFO):     2017-03-23 06:00:00: Paper trader simulated a SELL      955.57507773 USDT <= 0.00000000 BTC
    2017-11-03 20:07:34 (INFO):     2017-03-23 06:30:00: Paper trader simulated a BUY       0.00000000 USDT => 0.91424182 BTC
    2017-11-03 20:07:34 (INFO):     2017-03-25 16:00:00: Paper trader simulated a SELL      879.57949836 USDT <= 0.00000000 BTC
    2017-11-03 20:07:34 (INFO):     2017-03-29 12:30:00: Paper trader simulated a BUY       0.00000000 USDT => 0.85200459 BTC
    2017-11-03 20:07:36 (INFO):     2017-04-14 17:30:00: Paper trader simulated a SELL      1028.01340221 USDT <= 0.00000000 BTC
    2017-11-03 20:07:36 (INFO):     2017-04-19 05:00:00: Paper trader simulated a BUY       0.00000000 USDT => 0.81554640 BTC
    2017-11-03 20:07:39 (INFO):     2017-05-15 16:00:00: Paper trader simulated a SELL      1452.07148661 USDT <= 0.00000000 BTC
    2017-11-03 20:07:39 (INFO):     2017-05-20 05:30:00: Paper trader simulated a BUY       0.00000000 USDT => 0.73383030 BTC
    2017-11-03 20:07:39 (INFO):     2017-05-20 12:30:00: Paper trader simulated a SELL      1483.03434478 USDT <= 0.00000000 BTC
    2017-11-03 20:07:39 (INFO):     2017-05-21 07:00:00: Paper trader simulated a BUY       0.00000000 USDT => 0.71847974 BTC
    2017-11-03 20:07:40 (INFO):     2017-05-28 18:30:00: Paper trader simulated a SELL      1475.02870381 USDT <= 0.00000000 BTC
    2017-11-03 20:07:40 (INFO):     2017-06-01 11:30:00: Paper trader simulated a BUY       0.00000000 USDT => 0.65425717 BTC
    2017-11-03 20:07:40 (INFO):     2017-06-01 15:00:00: Paper trader simulated a SELL      1511.52080486 USDT <= 0.00000000 BTC
    2017-11-03 20:07:40 (INFO):     2017-06-01 16:30:00: Paper trader simulated a BUY       0.00000000 USDT => 0.65587144 BTC

------------------------------------------------------------------------------------

    2017-11-03 20:19:56 (INFO):     2017-01-01 00:09:00: Paper trader simulated a SELL      963.59005887 USDT <= 0.00000000 BTC
    2017-11-03 20:19:57 (INFO):     2017-01-02 16:39:00: Paper trader simulated a BUY       0.00000000 USDT => 0.94559352 BTC
    2017-11-03 20:19:57 (INFO):     2017-01-07 17:39:00: Paper trader simulated a SELL      855.56997208 USDT <= 0.00000000 BTC
    2017-11-03 20:19:58 (INFO):     2017-01-16 17:39:00: Paper trader simulated a BUY       0.00000000 USDT => 1.03152982 BTC
    2017-11-03 20:19:59 (INFO):     2017-01-26 03:09:00: Paper trader simulated a SELL      928.06428446 USDT <= 0.00000000 BTC
    2017-11-03 20:20:00 (INFO):     2017-01-29 08:09:00: Paper trader simulated a BUY       0.00000000 USDT => 1.00784347 BTC
    2017-11-03 20:20:01 (INFO):     2017-02-10 22:09:00: Paper trader simulated a SELL      1006.66232118 USDT <= 0.00000000 BTC
    2017-11-03 20:20:02 (INFO):     2017-02-15 00:39:00: Paper trader simulated a BUY       0.00000000 USDT => 0.99965074 BTC
    2017-11-03 20:20:04 (INFO):     2017-03-09 09:09:00: Paper trader simulated a SELL      1181.21930321 USDT <= 0.00000000 BTC
    2017-11-03 20:20:05 (INFO):     2017-03-15 08:09:00: Paper trader simulated a BUY       0.00000000 USDT => 0.94767222 BTC
    2017-11-03 20:20:05 (INFO):     2017-03-19 07:09:00: Paper trader simulated a SELL      944.63697273 USDT <= 0.00000000 BTC
    2017-11-03 20:20:06 (INFO):     2017-03-22 08:39:00: Paper trader simulated a BUY       0.00000000 USDT => 0.92245371 BTC
    2017-11-03 20:20:06 (INFO):     2017-03-23 05:39:00: Paper trader simulated a SELL      964.78881901 USDT <= 0.00000000 BTC
    2017-11-03 20:20:06 (INFO):     2017-03-23 07:09:00: Paper trader simulated a BUY       0.00000000 USDT => 0.92060353 BTC
    2017-11-03 20:20:06 (INFO):     2017-03-25 15:39:00: Paper trader simulated a SELL      879.62304799 USDT <= 0.00000000 BTC
    2017-11-03 20:20:07 (INFO):     2017-03-29 12:39:00: Paper trader simulated a BUY       0.00000000 USDT => 0.84931821 BTC
    2017-11-03 20:20:09 (INFO):     2017-04-14 17:09:00: Paper trader simulated a SELL      1023.08530123 USDT <= 0.00000000 BTC
    2017-11-03 20:20:09 (INFO):     2017-04-19 04:39:00: Paper trader simulated a BUY       0.00000000 USDT => 0.81164973 BTC
    2017-11-03 20:20:12 (INFO):     2017-05-15 16:39:00: Paper trader simulated a SELL      1439.83818081 USDT <= 0.00000000 BTC
    2017-11-03 20:20:13 (INFO):     2017-05-20 05:09:00: Paper trader simulated a BUY       0.00000000 USDT => 0.72537026 BTC
    2017-11-03 20:20:13 (INFO):     2017-05-20 12:39:00: Paper trader simulated a SELL      1467.38486616 USDT <= 0.00000000 BTC
    2017-11-03 20:20:13 (INFO):     2017-05-21 07:09:00: Paper trader simulated a BUY       0.00000000 USDT => 0.71327921 BTC
    2017-11-03 20:20:13 (INFO):     2017-05-21 23:09:00: Paper trader simulated a SELL      1492.04315770 USDT <= 0.00000000 BTC
    2017-11-03 20:20:13 (INFO):     2017-05-22 04:09:00: Paper trader simulated a BUY       0.00000000 USDT => 0.71522232 BTC
    2017-11-03 20:20:14 (INFO):     2017-05-28 18:39:00: Paper trader simulated a SELL      1467.55957069 USDT <= 0.00000000 BTC
    2017-11-03 20:20:14 (INFO):     2017-06-01 11:09:00: Paper trader simulated a BUY       0.00000000 USDT => 0.64892532 BTC
    2017-11-03 20:20:14 (INFO):     2017-06-01 15:39:00: Paper trader simulated a SELL      1500.75700330 USDT <= 0.00000000 BTC
    2017-11-03 20:20:14 (INFO):     2017-06-01 16:39:00: Paper trader simulated a BUY       0.00000000 USDT => 0.64970159 BTC
    2017-11-03 20:20:16 (INFO):     2017-06-14 06:09:00: Paper trader simulated a SELL      1731.64233218 USDT <= 0.00000000 BTC

*edit*
then looking some more at the buys and sells for these two backtests there seems to be some funkiness going on with the times and dates

**Comment by bbjay** [comment] 2017-11-09 12:49
we had a similar, if not identical, discussion over here #1142

**Closed as completed** 2018-10-31 23:23 UTC
Labels: wontfix
