### ISSUE TITLE
Gekko is able to serve on server but browser refused to connect.

### ISSUE THREAD

**Issue by claytonchew** [askmike/gekko#2195] opened 2018-05-19 20:29 UTC
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[/] bug report
[ ] question about the decisions made in the repository

**Action taken**

1. Start up an instance 'Ubuntu 16.04 LTS HWM' from AWS.
2. Set up elastic IP address and associate with the instance.
3. Set up DNS to have my custom domain pointing to the IP address.
4. Allow inbound http port `3000` and `443`.
5. SSH into the instance and get it all setup.
6. Setup nginx, SSL and htpasswd as per [Configuring Gekko to run in the cloud](https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html#Configuring-Gekko-to-run-in-the-cloud)

nginx config:
```
server {
    listen 80;
    listen [::]:80;
    server_name mysecretdomain.com;
    return 301 https://$server_name$request_uri;
}

upstream websocket {
    server localhost:3000;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    root /var/www/html;

    ssl_certificate /etc/letsencrypt/live/mysecretdomain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mysecretdomain.com/privkey.pem;
    add_header Strict-Transport-Security "max-age=31536000";

    location / {
            proxy_buffers 8 32k;
            proxy_buffer_size 64k;

            proxy_pass http://websocket;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-NginX-Proxy true;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_read_timeout 86400s;
            proxy_send_timeout 86400s;

            auth_basic "Restricted Content";
            auth_basic_user_file /etc/nginx/.htpasswd;
    }
}
```
nginx version: nginx/1.10.3 (Ubuntu)

UIConfig.js:
```javascript
const CONFIG = {
  headless: true,
  api: {
    host: '127.0.0.1',  // I also tried 0.0.0.0
    port: 3000,
    timeout: 120000 // 2 minutes
  },
  ui: {
    ssl: true,
    host: 'mysecretdomain.com',
    port: 443,
    path: '/'
  },
  adapter: 'sqlite'
}

if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;
```

**Expected result** 

Expected to work flawlessly.

**Actual result**

```
node gekko --ui
Serving Gekko UI on https://mysecretdomain.com:443/
```
Accessing `https://mysecretdomain.com:443/` on web browser gives me **ERR_CONNECTION_REFUSED**

**Other information**

Bypassing SSL and ngix seems to work but it's not secure with the UIConfig.js below:

```javascript
const CONFIG = {
  headless: true,
  api: {
    host: '0.0.0.0',
    port: 3000,
    timeout: 120000 // 2 minutes
  },
  ui: {
    ssl: false,
    host: 'mysecretdomain.com',
    port: 3000,
    path: '/'
  },
  adapter: 'sqlite'
}

if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;
```

It works with api host `0.0.0.0`. However, doesn't work with api host `127.0.0.1`.

**Comment by askmike** [comment] 2018-05-20 12:39
> It works with api host 0.0.0.0. However, doesn't work with api host 127.0.0.1.

~So you don't have this issue with 0.0.0.0? In that case we should simply update the docs?~

Misread the issue.

-----

If you use nginx to serve anything else (over the same port), does that work? Are there messages in the nginx error log?

**Comment by askmike** [comment] 2018-05-20 12:44
Some context, using nginx you want to up with this setup:

    [ your browser with Gekko UI] --https--> [ nginx ] --http--> [ gekko ]

The error you are seeing on the far left is a bit vague, in order to fix I'd recommand debugging this further to figure out whether your browser can connect to nginx, and whether nginx can connect to gekko. I'd start with nginx logs.

Unfortunately I am trying to tidy up the issue tracker, this seems like an installation / configuration issue, not a bug in Gekko. As such I am closing this, if you're unable to figure it out based on the server logs please ask around on the forum: https://forum.gekko.wizb.it/

**Closed as completed by askmike** 2018-05-20 12:44 UTC
Labels: waiting-for-answer

**Comment by itsXactlY** [comment] 2020-02-03 06:25
Remove anything in host ''

host: '',  // like this, and remote access works.
