### ISSUE TITLE
SQLITE_IOERR: disk I/O error

### ISSUE THREAD

**Issue by Ales11** [askmike/gekko#1393] opened 2017-12-01 14:19 UTC
* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Ive installed Gekko on my Computer with Win10 and Bash from https://gekko.wizb.it/docs/installation/installing_gekko_on_windows_with_bash_on_windows_10.html

Ive changed handle.js
db.run('PRAGMA journal_mode = ' + config.splite.journalMode||'WAL' );
to
db.run('PRAGMA journal_mode = DEL' ); 
as it was showed in tutorial.

When I was trying to add data, it shows this bug:
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_IOERR: disk I/O error
    at Error (native)

And when Ive been trying to run LiveBot it showed form:
GEKKO ERROR: 
 ERROR: Error: SQLITE_READONLY: attempt to write a readonly database

And in bash:
 ERROR: Error: SQLITE_READONLY: attempt to write a readonly database

* **Expected result** (what you hoped would happen)
I think, there is some problem with databases rights, but I am unable to find it and change it.

**Comment by cmroche** [comment] 2017-12-02 02:22
Probably a duplicate of #1375 and #1373, sync the develop branch and try testing with Pull Request #1369. If you do this, please let us know if it resolved your problem.

**Comment by nareddyt** [comment] 2017-12-08 16:34
Is this issue resolved? I checked out the `develop` branch but still run into this error.

 <-- POST /api/scansets
  <-- GET /api/strategies
  <-- GET /api/configPart/paperTrader
  <-- GET /api/configPart/performanceAnalyzer
  --> GET /api/configPart/paperTrader 200 15ms 132b
  --> GET /api/configPart/performanceAnalyzer 200 15ms 144b
  --> GET /api/strategies 200 130ms 2.02kb
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_IOERR: disk I/O error
    at Error (native)
  --> POST /api/scansets 200 878ms 82b

I am on bash for windows 10.

**Comment by cmroche** [comment] 2017-12-08 23:55
@nareddyt Please delete all the files in your history folder and rerun the import. Your sqlite DB is corrupt (a problem prior to PR #1369) and can no longer be loaded now that we've forced DELETE/PERSIST journaling on Windows.

**Comment by nareddyt** [comment] 2017-12-09 00:01
Thanks!

**Comment by rafaelcla** [comment] 2017-12-14 17:56
What is the address of the history folder?

**Comment by rafaelcla** [comment] 2017-12-14 18:31
At where?

**Comment by cmroche** [comment] 2017-12-16 14:53
@rafaelcla The folder is called "history" in your gekko folder, this is assuming you didn't set it to something else in your configuration file.

**Closed as completed** 2018-11-01 01:36 UTC
Labels: wontfix
