### ISSUE TITLE
GDAX ERROR: { message: 'NotFound' }

### ISSUE THREAD

**Issue by GuyPaddock** [askmike/gekko#984] opened 2017-08-16 20:23 UTC
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Running MACD strategy on GDAX since around 9 AM EDT this morning.

* **Expected result** (what you hoped would happen)
BUY & SELL trades would happen without error.

* **Actual result** (unexpected outcome)
Errors started appearing after a partial SELL order that Gekko canceled and reissued:
```
2017-08-16 15:53:19 (DEBUG):    Requested BTC/USD trade data from GDAX ...
2017-08-16 15:53:19 (DEBUG):    Processing 4 new trades. From 2017-08-16 19:53:02 UTC to 2017-08-16 19:53:13 UTC. (a few seconds)
2017-08-16 15:53:19 (DEBUG):    calculated MACD properties for candle:
2017-08-16 15:53:19 (DEBUG):             short: 4277.07949205
2017-08-16 15:53:19 (DEBUG):             long: 4236.80897401
2017-08-16 15:53:19 (DEBUG):             macd: 40.27051805
2017-08-16 15:53:19 (DEBUG):             signal: 43.91434507
2017-08-16 15:53:19 (DEBUG):             macdiff: -3.64382702
2017-08-16 15:53:19 (DEBUG):    In downtrend since 1 candle(s)

2017-08-16 15:53:19 (INFO):     We have new trading advice!
2017-08-16 15:53:19 (INFO):              Position: short
2017-08-16 15:53:19 (INFO):              Market price: 4292.17
2017-08-16 15:53:19 (INFO):              Based on market time: 2017-08-16 19:52:00

2017-08-16 15:53:19 (INFO):     Trader Received advice to go short. Selling  BTC
2017-08-16 15:53:20 (INFO):     Attempting to SELL 0.02123971 BTC at GDAX price: 4292.17
2017-08-16 15:53:39 (DEBUG):    Requested BTC/USD trade data from GDAX ...
2017-08-16 15:53:40 (DEBUG):    Processing 6 new trades. From 2017-08-16 19:53:22 UTC to 2017-08-16 19:53:39 UTC. (a few seconds)
2017-08-16 15:53:59 (DEBUG):    Requested BTC/USD trade data from GDAX ...
2017-08-16 15:53:59 (DEBUG):    Processing 6 new trades. From 2017-08-16 19:53:42 UTC to 2017-08-16 19:54:01 UTC. (a few seconds)
2017-08-16 15:54:19 (DEBUG):    Requested BTC/USD trade data from GDAX ...
2017-08-16 15:54:19 (DEBUG):    Processing 6 new trades. From 2017-08-16 19:54:05 UTC to 2017-08-16 19:54:21 UTC. (a few seconds)
2017-08-16 15:54:21 (INFO):     SELL order was not (fully) filled, cancelling and creating new order
2017-08-16 15:54:26 (INFO):     Attempting to SELL 0.02123971 BTC at GDAX price: 4292.17
2017-08-16 15:54:39 (DEBUG):    Requested BTC/USD trade data from GDAX ...
2017-08-16 15:54:39 (DEBUG):    Processing 22 new trades. From 2017-08-16 19:54:21 UTC to 2017-08-16 19:54:33 UTC. (a few seconds)
2017-08-16 15:54:59 (DEBUG):    Requested BTC/USD trade data from GDAX ...
2017-08-16 15:54:59 (DEBUG):    Processing 6 new trades. From 2017-08-16 19:54:41 UTC to 2017-08-16 19:55:00 UTC. (a few seconds)
2017-08-16 15:55:19 (DEBUG):    Requested BTC/USD trade data from GDAX ...
2017-08-16 15:55:19 (DEBUG):    Processing 3 new trades. From 2017-08-16 19:55:01 UTC to 2017-08-16 19:55:21 UTC. (a few seconds)
2017-08-16 15:55:26 (INFO):     SELL was successfull
2017-08-16 15:55:26 (ERROR):    GDAX ERROR: { message: 'NotFound' }
2017-08-16 15:55:26 (DEBUG):    GDAX returned an error, retrying..
2017-08-16 15:55:37 (ERROR):    GDAX ERROR: { message: 'NotFound' }
2017-08-16 15:55:37 (DEBUG):    GDAX returned an error, retrying..
2017-08-16 15:55:39 (DEBUG):    Requested BTC/USD trade data from GDAX ...
2017-08-16 15:55:39 (DEBUG):    Processing 12 new trades. From 2017-08-16 19:55:21 UTC to 2017-08-16 19:55:35 UTC. (a few seconds)
2017-08-16 15:55:47 (ERROR):    GDAX ERROR: { message: 'NotFound' }
2017-08-16 15:55:47 (DEBUG):    GDAX returned an error, retrying..
2017-08-16 15:55:57 (ERROR):    GDAX ERROR: { message: 'NotFound' }
2017-08-16 15:55:57 (DEBUG):    GDAX returned an error, retrying..
2017-08-16 15:55:59 (DEBUG):    Requested BTC/USD trade data from GDAX ...
2017-08-16 15:55:59 (DEBUG):    Processing 3 new trades. From 2017-08-16 19:55:42 UTC to 2017-08-16 19:55:59 UTC. (a few seconds)
```

The error continued throughout the rest of the logs. I had to stop and restart Gekko CLI.

* **Other information**
I am on the `stable` branch.

**Comment by pelletencate** [comment] 2017-08-16 21:45
Possible dupe of #980

**Comment by askmike** [comment] 2017-08-16 21:52
Ah yes def! See #980 for further discussion.

**Closed as completed by askmike** 2017-08-16 21:52 UTC
