### ISSUE TITLE
Backtester date time per candle isn't correct

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#681] opened 2017-04-09 10:31 UTC
This is with the backtester set to 1 minute, the _i and _d should reflect each minute, it's kind of doing it in lumps of 50, it's odd.

[Number: 1484671020000]
  _i: 1484671020000,
  _f: undefined,
  _l: undefined,
  _strict: undefined,
  _isUTC: false,
  _pf: 
   { empty: false,
     unusedTokens: [],
     unusedInput: [],
     overflow: -2,
     charsLeftOver: 0,
     nullInput: false,
     invalidMonth: null,
     invalidFormat: false,
     userInvalidated: false,
     iso: false },
  _d: 2017-01-17T16:37:00.000Z }
[Number: 1484671020000]
  _i: 1484671020000,
  _f: undefined,
  _l: undefined,
  _strict: undefined,
  _isUTC: false,
  _pf: 
   { empty: false,
     unusedTokens: [],
     unusedInput: [],
     overflow: -2,
     charsLeftOver: 0,
     nullInput: false,
     invalidMonth: null,
     invalidFormat: false,
     userInvalidated: false,
     iso: false },
  _d: 2017-01-17T16:37:00.000Z }

**Comment by askmike** [comment] 2017-04-09 10:46
The `_d` and `_i` are internal properties of the moment object (date library Gekko uses). If you want to say anything about those dates please log them like so (to make sure to take care of daylight saving time / timezone / etc):

    candle.start.format() // in human readable string
    candle.start.unix() // in unix timestamp

What you are logging here seems to me like 2 date objects referring to the same time. Where do you get the 50 number from? And please share where you are logging these dates.

**Comment by thegamecat** [comment] 2017-04-09 17:12
Ok sorry, there is a lot of detail to go through. 

1)Using a 1 minute backtest I use the method.check = function() { to write out the outputs (see attachment)
[writer.txt](https://github.com/askmike/gekko/files/908386/writer.txt)
 from my strategy and the _i and _d. Logically I am expecting to see _i looking like this:

1491461640,strat var val x,strat var val y
"1491461700", etc
"1491461760"
"1491461820"
"1491461880"
"1491461940"
"1491462000"
"1491462060"
"1491462120"
"1491462180"
"1491462240"
"1491462300"
"1491462360"
"1491462420"
"1491462480"
"1491462540"
"1491462600"
"1491462660"
"1491462720"
"1491462780"
"1491462840"
"1491462900"
"1491462960"

2) What I actually see in my output csv is nothing like this, instead I see this:

1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491463620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491466620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000
1491469620000

I see the same thing when I write to console. The _d variable looks like:
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 07:37:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 08:27:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 09:17:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)
Thu Apr 06 2017 10:07:00 GMT+0100 (DST)


Now interestingly, if I set the backtest to 1 hour it gives me the correct datetime:

Sat Apr 01 2017 09:58:00 GMT+0100 (DST)
Sat Apr 01 2017 10:58:00 GMT+0100 (DST)
Sat Apr 01 2017 11:58:00 GMT+0100 (DST)
Sat Apr 01 2017 12:58:00 GMT+0100 (DST)
Sat Apr 01 2017 13:58:00 GMT+0100 (DST)
Sat Apr 01 2017 14:58:00 GMT+0100 (DST)
Sat Apr 01 2017 15:58:00 GMT+0100 (DST)
Sat Apr 01 2017 16:58:00 GMT+0100 (DST)
Sat Apr 01 2017 17:58:00 GMT+0100 (DST)
Sat Apr 01 2017 18:58:00 GMT+0100 (DST)
Sat Apr 01 2017 19:58:00 GMT+0100 (DST)
Sat Apr 01 2017 20:58:00 GMT+0100 (DST)
Sat Apr 01 2017 21:58:00 GMT+0100 (DST)
Sat Apr 01 2017 22:58:00 GMT+0100 (DST)
Sat Apr 01 2017 23:58:00 GMT+0100 (DST)
Sun Apr 02 2017 00:58:00 GMT+0100 (DST)
Sun Apr 02 2017 01:58:00 GMT+0100 (DST)
Sun Apr 02 2017 02:58:00 GMT+0100 (DST)
Sun Apr 02 2017 03:58:00 GMT+0100 (DST)
Sun Apr 02 2017 04:58:00 GMT+0100 (DST)
Sun Apr 02 2017 05:58:00 GMT+0100 (DST)
Sun Apr 02 2017 06:58:00 GMT+0100 (DST)
Sun Apr 02 2017 07:58:00 GMT+0100 (DST)
Sun Apr 02 2017 08:58:00 GMT+0100 (DST)
Sun Apr 02 2017 09:58:00 GMT+0100 (DST)
Sun Apr 02 2017 10:58:00 GMT+0100 (DST)
Sun Apr 02 2017 11:58:00 GMT+0100 (DST)
Sun Apr 02 2017 12:58:00 GMT+0100 (DST)
Sun Apr 02 2017 13:58:00 GMT+0100 (DST)
Sun Apr 02 2017 14:58:00 GMT+0100 (DST)
Sun Apr 02 2017 15:58:00 GMT+0100 (DST)
Sun Apr 02 2017 16:58:00 GMT+0100 (DST)
Sun Apr 02 2017 17:58:00 GMT+0100 (DST)
Sun Apr 02 2017 18:58:00 GMT+0100 (DST)
Sun Apr 02 2017 19:58:00 GMT+0100 (DST)
Sun Apr 02 2017 20:58:00 GMT+0100 (DST)
Sun Apr 02 2017 21:58:00 GMT+0100 (DST)
Sun Apr 02 2017 22:58:00 GMT+0100 (DST)
Sun Apr 02 2017 23:58:00 GMT+0100 (DST)
Mon Apr 03 2017 00:58:00 GMT+0100 (DST)
Mon Apr 03 2017 01:58:00 GMT+0100 (DST)
Mon Apr 03 2017 02:58:00 GMT+0100 (DST)
Mon Apr 03 2017 03:58:00 GMT+0100 (DST)
Mon Apr 03 2017 04:58:00 GMT+0100 (DST)
Mon Apr 03 2017 05:58:00 GMT+0100 (DST)

As a side note - remember when we found that the backtester would break with 1 minute candles over a long period of time? Well what the file writer has shown is when the Backtest button becomes active again in the UI (ie when we think the backtester stops), the backtest keeps running on the server side, AND starts a new instance.

**Comment by askmike** [comment] 2017-04-09 17:17
I need more info than this, I have no idea what you are doing with Gekko haha.

> What I actually see in my output csv

- What version of Gekko are you running?
- What strategy are you using?
- What adapter are you using?
- What output CSV? Can you post (and indent) that code? Gekko doesn't output CSV files.
- Where did you get the market data from?
- If you are using the commandline (or API), please post the full config, If the UI please post screenshots.

**Comment by thegamecat** [comment] 2017-04-09 17:25
Hah ok, sorry....

This is master / latest version / latest node /sqlite
It's a strategy I have written using talib, but I've used the writer for all talib strategies and same issue. 
I wrote a csv writer (see code above).
This happens with all market data I have imported from poloniex via gekko.
I'm running UI, but same thing happens whether I use server and my own route (ie api call). 

In summary, if the candle size is 1 minute, the _i _d values come back very oddly (see point 1 and 2), if the candle size is 1 hour the _i _d values come back as expected see above. 

Update: it's basically an issue with any candle size in minutes whereas Days and Hours work as expected.

I'm happy to share screens in skype if you like and I can walk you through it all (and show you some other stuff :))

**Comment by askmike** [comment] 2017-04-10 12:07
You are doing some funky things, if we want to debug this can we first verify wether your Gekko is working as intended?

Please run this strat: https://gist.github.com/askmike/5c8fbfdb9667cd53e030770c5393347d
and configure it to use 1m candles. For me this is working fine:

    2017-04-10 13:02:18 (INFO):   WARNING: BACKTESTING FEATURE NEEDS PROPER TESTING
    2017-04-10 13:02:18 (INFO):   WARNING: ACT ON THESE NUMBERS AT YOUR OWN RISK!

    2016-12-19T00:39:00+00:00
    2016-12-19T00:40:00+00:00
    2016-12-19T00:41:00+00:00
    2016-12-19T00:42:00+00:00
    2016-12-19T00:43:00+00:00
    2016-12-19T00:44:00+00:00
    2016-12-19T00:45:00+00:00
    2016-12-19T00:46:00+00:00
    2016-12-19T00:47:00+00:00
    2016-12-19T00:48:00+00:00
    2016-12-19T00:49:00+00:00
    2016-12-19T00:50:00+00:00
    2016-12-19T00:51:00+00:00
    2016-12-19T00:52:00+00:00
    2016-12-19T00:53:00+00:00
    2016-12-19T00:54:00+00:00
    (...)

If that is also working for you:

Your writer.txt code is blocking the node event loop (the appendToFileSync call). Please write to file async (or use streams).

**Comment by askmike** [comment] 2017-04-10 12:08
I am closing this under the assumption that your code is breaking candle func (if only 1m is not working but everything else is it is most likely related to some race conditions on some IO). We can still work to resolving this, but it's not an issue with Gekko (if it is we can reopen).

**Closed as completed by askmike** 2017-04-10 12:08 UTC

**Comment by thegamecat** [comment] 2017-04-10 23:53
You are correct in so much as 2 appendFileSync seem to be creating a block! 
Taking one of them (the one that makes the file header) resolves the issue.

**Comment by southerton81** [comment] 2017-04-27 19:22
I have encountered the same problem, it manifests when I add talib indicator to mock strategy. Tested on 1m and 15m candles and it produces gaps in the log. 1 hour candles work ok. 

```
var strat = {};

strat.init = function() {

  var settingsSMA = {
    optInTimePeriod: 20
  }

  this.addTalibIndicator('mysma', 'sma', settingsSMA);
}

strat.update = function(candle) {}

strat.log = function() {}
strat.check = function(candle) {
  console.log(candle.start.format());
}

module.exports = strat;

```


> 2017-04-27T20:54:00+03:00
2017-04-27T20:54:00+03:00
2017-04-27T20:54:00+03:00
2017-04-27T20:54:00+03:00
2017-04-27T20:54:00+03:00
2017-04-27T20:54:00+03:00
2017-04-27T20:54:00+03:00
2017-04-27T21:02:00+03:00
2017-04-27T21:02:00+03:00
