### ISSUE TITLE
Gekko UI doesn't show running trades

### ISSUE THREAD

**Issue by xbromy** [askmike/gekko#2184] opened 2018-05-17 06:23 UTC
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I've startet neuronal strategy with slim, short trade config using UI. And it's trading (I can see in logs and on Binance). But the UI says 0 trades. Same strategy on another instance of gekko is showing results... 

**Expected result** (what you hoped would happen)
trades are shown in UI

**Actual result** (unexpected outcome)
0 trades are shown

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by ghost** [comment] 2018-05-17 16:02
https://github.com/askmike/gekko/issues/2107

**Comment by xbromy** [comment] 2018-05-18 19:29
Hm, one observation: I've now started the run by using commandline with configfile and active TelegramBot which is working with RSI. The gekko is trading but not notifing me by Telegram. So is it a problem of "neuronal" strategy? https://github.com/zschro/gekko-neuralnet

**Comment by alvarheras** [comment] 2018-05-23 05:33
I don't think it's a problem with the neural strategy, I have a RSI-based strategy running live against a pair of binances (ICN/BTC) and the orders are not reflected in the ui of gekko either. Can it be a matter of the live order being late to completion and the information not being collected?

**Comment by askmike** [comment] 2018-05-23 15:47
duplicate of #2107.

**Comment by askmike** [comment] 2018-05-23 15:48
It has nothing to do with the strategy, there are some bugs in Gekko I am working on right now.

**Closed as completed by askmike** 2018-05-23 15:47 UTC
