### ISSUE TITLE
Error while requesting trade data from okcoin.cn

### ISSUE THREAD

**Issue by szeloof** [askmike/gekko#546] opened 2017-01-14 14:09 UTC
Hi,
I have gekko running on a 32 bit install of ubuntu, it works great with every other exchange but will not start trading with okcoin. I have checked that my api key, secret, and username are correct and in okcoin allowed the permissions "trade" and "withdraw" for the api key. 

See below for debug log. Notice the end of it, "okcoin returned an error, retrying.." This will go on for ever and never fetch the trade data.  

```
2017-01-14` 09:01:35 (INFO):     Gekko v0.3.4 started
2017-01-14 09:01:35 (INFO):     I'm gonna make you rich, Bud Fox. 


2017-01-14 09:01:35 (INFO):     Setting up Gekko in realtime mode
2017-01-14 09:01:35 (INFO):
2017-01-14 09:01:35 (INFO):     Setting up:
2017-01-14 09:01:35 (INFO):              Candle writer
2017-01-14 09:01:35 (INFO):              Store candles in a database
2017-01-14 09:01:35 (INFO):

2017-01-14 09:01:35 (INFO):     Setting up:
2017-01-14 09:01:35 (INFO):              Trading Advisor
2017-01-14 09:01:35 (INFO):              Calculate trading advice
2017-01-14 09:01:35 (INFO):              Using the trading method: MACD
2017-01-14 09:01:35 (WARN):     Warning, trading method has no name
2017-01-14 09:01:35 (INFO):

2017-01-14 09:01:35 (INFO):     Setting up:
2017-01-14 09:01:35 (INFO):              Trader
2017-01-14 09:01:35 (INFO):              Follows the advice and create real orders.
2017-01-14 09:01:35 (DEBUG):    getting balance & fee from okcoin
2017-01-14 09:01:35 (INFO):

2017-01-14 09:01:37 (INFO):     trading at okcoin ACTIVE
2017-01-14 09:01:37 (INFO):     okcoin trading fee will be: 0.1%
2017-01-14 09:01:37 (INFO):     okcoin portfolio:
2017-01-14 09:01:37 (INFO):              BTC: (removed)
2017-01-14 09:01:37 (INFO):              CNY: (removed)
2017-01-14 09:01:37 (INFO):              LTC: 0.000000000000
2017-01-14 09:01:37 (INFO):     Setting up:
2017-01-14 09:01:37 (INFO):              Advice logger
2017-01-14 09:01:37 (INFO):              
2017-01-14 09:01:37 (INFO):     Starting to watch the market: OkCoin /
2017-01-14 09:01:37 (DEBUG):    scheduling ticks
2017-01-14 09:01:37 (DEBUG):    Requested / trade data from OkCoin ...
2017-01-14 09:01:38 (DEBUG):    okcoin returned an error, retrying..
2017-01-14 09:01:39 (DEBUG):    Requested / trade data from OkCoin ...
2017-01-14 09:01:40 (DEBUG):    okcoin returned an error, retrying..
2017-01-14 09:01:41 (DEBUG):    Requested / trade data from OkCoin ...
2017-01-14 09:01:42 (DEBUG):    okcoin returned an error, retrying..
2017-01-14 09:01:43 (DEBUG):    Requested / trade data from OkCoin ...
2017-01-14 09:01:44 (DEBUG):    okcoin returned an error, retrying..
2017-01-14 09:01:45 (DEBUG):    Requested / trade data from OkCoin ...
2017-01-14 09:01:46 (DEBUG):    okcoin returned an error, retrying..
```

Here's my full config file: http://pastebin.com/jfbm5zzi

Thanks!

**Comment by jrcps** [comment] 2017-01-16 16:24
I have the same problem here. Bump.

**Comment by Bzzz666** [comment] 2017-01-17 00:38
same for me

**Comment by meirarc** [comment] 2017-01-17 01:15
same for me

**Comment by tregismoreira** [comment] 2017-01-19 10:15
Same here. I debugged and got the complete error:

```
unable to process order: { VError: OKCoin.executeRequest() HTTP status code 403 returned from GET request to url https://www.okcoin.cn/api/v1/trades.do with parameters {"symbol":"btc_cny","since":600}
    at Request._callback (/Users/thiagoregis/Bot/gekko/node_modules/okcoin-china/rest.js:132:21)
    at Request.self.callback (/Users/thiagoregis/Bot/gekko/node_modules/okcoin-china/node_modules/request/request.js:198:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/thiagoregis/Bot/gekko/node_modules/okcoin-china/node_modules/request/request.js:1035:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/thiagoregis/Bot/gekko/node_modules/okcoin-china/node_modules/request/request.js:962:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
  jse_shortmsg: 'OKCoin.executeRequest() HTTP status code 403 returned from GET request to url https://www.okcoin.cn/api/v1/trades.do with parameters {"symbol":"btc_cny","since":600}',
  jse_summary: 'OKCoin.executeRequest() HTTP status code 403 returned from GET request to url https://www.okcoin.cn/api/v1/trades.do with parameters {"symbol":"btc_cny","since":600}',
  message: 'OKCoin.executeRequest() HTTP status code 403 returned from GET request to url https://www.okcoin.cn/api/v1/trades.do with parameters {"symbol":"btc_cny","since":600}',
  name: 403 }
```

**Comment by greenbigfrog** [comment] 2017-12-14 10:21
Is this still an issue? looks a bit like a duplicate of #1008

**Comment by askmike** [comment] 2018-07-09 15:06
Unfortunately OKcoin is not enabled for now..

**Closed as completed by askmike** 2018-07-09 15:06 UTC
