### ISSUE TITLE
Problem with Gekko data importing

### ISSUE THREAD

**Issue by vlad3609** [askmike/gekko#869] opened 2017-07-21 07:47 UTC
Good afternoon everyone,

First of all big thanks for such a great tool!

Now to my problem, if anyone has the solution, I'd really appreciate your help. 
It's my second computer, where I'm installing gekko. The system is Macintosh, MacOs Sierra, MacBook Pro. Though it doesn't seem to be any problems at the first one, there's at the second. 
In order to install gekko, firstly I preinstalled nodejs and then followed certain commands for the app installation (like in your youtube video). 
Then I'm trying to import data from polonium and here is the result. Actually it's the same with all the options.

<img width="1041" alt="1" src="https://user-images.githubusercontent.com/30337216/28453894-ca7d8854-6e01-11e7-8192-48acd7588d5f.png">
<img width="492" alt="2" src="https://user-images.githubusercontent.com/30337216/28453895-caa759d6-6e01-11e7-80c2-c6a0a2698c1a.png">
<img width="1060" alt="3" src="https://user-images.githubusercontent.com/30337216/28453896-caa874ba-6e01-11e7-9092-c3045980bf88.png">

My Firewall is turned off.

I'd really appreciate your help,
Have a good day, 
Cheers!

**Comment by JohannesFerner** [comment] 2017-07-21 10:54
What does the Node console print out?

**Comment by vlad3609** [comment] 2017-07-21 14:12
<img width="572" alt="screen shot 2017-07-21 at 17 11 22" src="https://user-images.githubusercontent.com/30337216/28467220-d2ca642e-6e37-11e7-8cde-91dc67d3dff6.png">

**Comment by vlad3609** [comment] 2017-07-22 06:22
Any ideas?

**Comment by askmike** [comment] 2017-07-22 16:45
Very strange..

Can you open this file: https://github.com/askmike/gekko/blob/stable/web/routes/baseConfig.js

and set line 9 and 10 like so:

    config.silent = false;
    config.debug = true;

and rerun and post output?

**Comment by vlad3609** [comment] 2017-07-22 17:42
Sure, here it is:
<img width="547" alt="screen shot 2017-07-22 at 20 42 10" src="https://user-images.githubusercontent.com/30337216/28493363-4979616a-6f1e-11e7-8766-685ce22cab32.png">

Well, it doesn't look very different.
I tried different browsers, no difference.

**Comment by raffus** [comment] 2017-07-23 03:33
Are you running this native or through a VM machine?

Can you open this URL from your browser/console (or VM)?
https://poloniex.com/public?command=returnTicker

**Comment by vlad3609** [comment] 2017-07-23 07:22
No problems in accessing it (other than Google captcha). 
I just reinstalled my node.js same as gekko - and still there's same issue. If you wish I can give you an access to my laptop (via teamviewer).

**Comment by thegamecat** [comment] 2017-07-23 10:46
what happens if you try and run a back test through a CLI?

**Comment by askmike** [comment] 2017-07-23 11:40
If you are still having problems, please zip the history folder inside the gekko folder and email it to gekko@mvr.me.

**Comment by vlad3609** [comment] 2017-07-24 07:31
@askmike , sorry for the delay. You have them at your mail (there're 3: one which exists when app is off, second which I get after trying to import things and third empty). When I log out of the terminal two latest dbs disappear.

**Comment by vlad3609** [comment] 2017-07-24 07:31
@thegamecat what do you mean by the back test?

**Comment by askmike** [comment] 2017-07-25 15:29
@vlad3609 very strange, no data actually got imported. Can you download this file and put it in the gekko directory:

https://gist.github.com/askmike/4544cc88d24f926db58f2c2f09ce6b97

And than run this command:

    node gekko -c import.js -i

And after that try to scan using the UI. If that doesn't work, please post the logs of the gekko process.

**Comment by vlad3609** [comment] 2017-07-25 16:22
Sure, I'll do that.

**Comment by vlad3609** [comment] 2017-07-25 20:00
@askmike hah, very interesting:
<img width="730" alt="screen shot 2017-07-25 at 22 59 34" src="https://user-images.githubusercontent.com/30337216/28591051-0189cedc-718d-11e7-95eb-eb61d4d73355.png">

I sent the history at your email.

**Comment by askmike** [comment] 2017-07-25 20:06
Ah, what happens if you click on this link? https://poloniex.com/public?command=returnTradeHistory&currencyPair=USDT_BTC

**Comment by vlad3609** [comment] 2017-07-25 20:07
May captcha be the reason for this?

<img width="1280" alt="screen shot 2017-07-25 at 23 07 21" src="https://user-images.githubusercontent.com/30337216/28591351-11f670bc-718e-11e7-8ada-ff5929cb3728.png">

--

<img width="1280" alt="screen shot 2017-07-25 at 23 07 25" src="https://user-images.githubusercontent.com/30337216/28591364-21b0e7f8-718e-11e7-89f5-1cf2bca9fdbb.png">

**Comment by askmike** [comment] 2017-07-25 20:11
Ah there you go: Your issue is that your IP has been banned / flagged. Can you fill in the captcha until you see something like this:

<img width="1435" alt="screen shot 2017-07-25 at 21 10 14" src="https://user-images.githubusercontent.com/969743/28591457-b3ef2b9a-717d-11e7-9c2a-e407a838d84f.png">

Alternatively try to run Gekko from another IP or through a VPN :)

Feel free to comment, but In am closing this issue as the cause is your IP being banned.

**Closed as completed by askmike** 2017-07-25 20:11 UTC
Labels: waiting-for-answer

**Comment by mboremski** [comment] 2018-01-06 19:22
Could anyone give me a hint how to solve same problem in binance?
I am able to import data from poloniex (via CLI).
Changing exchange to binance leads to this error:
![grafik](https://user-images.githubusercontent.com/13338772/34643133-54e2bc60-f31f-11e7-8163-89a9a4fc6e80.png)

Maybe anyone can give me a URL to test output of binance (similar to the URL for poloniex in this post)
Thanks alot

**Comment by mboremski** [comment] 2018-01-06 22:14
Found my solution in  #1637.
Changed size of imported data from 1d to 1h.

**Comment by dmitriz** [comment] 2018-01-09 15:49
> Changed size of imported data from 1d to 1h.

Where does it need to be changed?

I am also having the same problem

**Comment by dmitriz** [comment] 2018-01-09 15:57
Ok, found it here:
https://github.com/askmike/gekko/blob/3159df10ca70a4951a7b3c155ce3d3092ac8833d/exchanges/binance.js#L97

**Comment by mboremski** [comment] 2018-01-09 16:27
Please watch for all changes regarding this made trough #1637.
This needs to be changed on several lines. (I found 3)
