### ISSUE TITLE
Backtest - roundtrips data doesn't look right

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#961] opened 2017-08-13 19:41 UTC
I write out the Roundtrips array to a file when the backtest completes. If you change the file extension from .txt to .csv you can see it in excel.

I don't understand some of the elements; for example row 14:
18/01/2016 05:54 | 18/01/2016 06:16 | 1.36238838 | 1.34651798 | 126.393 | 131.343 | 22 minutes | 4.94961195 | 3.91603604

Entry is higher than exit so surely this is a loss?

[test-all-1-poloniex-USDT-ETH-2017-08-13T17-55-56.410Z-roundtrips.txt](https://github.com/askmike/gekko/files/1220701/test-all-1-poloniex-USDT-ETH-2017-08-13T17-55-56.410Z-roundtrips.txt)

**Comment by askmike** [comment] 2017-08-13 19:46
Can you share the code you use to write to file?

**Comment by askmike** [comment] 2017-08-13 19:46
And if you run the same backtest in the UI, do you see the same numbers in the round trip table?

**Comment by thegamecat** [comment] 2017-08-13 19:48
[logger.txt](https://github.com/askmike/gekko/files/1220710/logger.txt)

**Comment by askmike** [comment] 2017-08-13 19:50
Did you edit the logger prototype? In that case I'd need to see either a diff to see what you have changed.. or a reproducible case of a backtest without any edited files.

**Comment by thegamecat** [comment] 2017-08-13 20:07
Dunno what a prototype is but you can see I've added the file writer and cleaned up the tabs. Trying to see if I can get the strat to work in ui. Not straight forward.

**Comment by askmike** [comment] 2017-08-13 20:09
Can you put in the original and your version here: https://www.diffchecker.com/ That way we can see what you changed.

My point is that if you go around and changing files inside Gekko, I first want to establish that this is indeed caused by Gekko and not caused by your changes.

**Comment by thegamecat** [comment] 2017-08-13 20:16
Yep, I'm with you. I'm trying to get the strat working on the UI first.

**Comment by thegamecat** [comment] 2017-08-13 20:19
Ok so I got this working in the UI and the issue is it doesn't write out the entry and exit price - which is what I added to mine. So there is actually no way of validating that the exit and exit balances as are they should be.

**Comment by askmike** [comment] 2017-08-13 20:20
Great! If you can reproduce this issue in the UI (with a un modified version of Gekko) I don't need diffs anymore :)

**Comment by thegamecat** [comment] 2017-08-13 20:21
https://www.diffchecker.com/N7gTUWB7

It's impossible to reproduce because the UI doesn't show entry and exit prices so you can't validate entry and exit balances are right or wrong. It's an invalid test.

**Comment by askmike** [comment] 2017-08-13 20:30
>  fsw.appendFileSync(fname, outtxt, encoding = 'utf8');

This line very likely messes things up. A gekko backtest relies on certain race conditions not happening, when you are blocking the event loop with sync file writes nothing is guarenteed anymore.

**Comment by thegamecat** [comment] 2017-08-13 20:41
haha you always say that :)

It's not causing any issues at all.

**Comment by thegamecat** [comment] 2017-08-13 20:47
If you write the entry / exit price and display it with the roundtrip you'll see it's the same.

**Comment by askmike** [comment] 2017-08-13 20:59
if you run a backtest via the API (or via the UI) the full roundtrip (incl. entry and exit price) are in the API response. Could you check there?

**Comment by thegamecat** [comment] 2017-08-13 21:03
I have, the values are the same.  The writer is not causing the issue.

**Comment by askmike** [comment] 2017-08-13 21:07
Could you make it reproducible for me as well? So either a standard strat or so?

I don't mean to be a pain, but if I can't reproduce I cannot fix this..

**Comment by thegamecat** [comment] 2017-08-13 21:09
Yep, I'm with you. I'll see what I can do.

**Comment by askmike** [comment] 2017-08-16 13:27
I am closing this as we can only properly test this after implementing #978 (me linking to that issue creates a reference there). If this is a bug after that new plugin we can reopen this one.

**Closed as completed by askmike** 2017-08-16 13:27 UTC
Labels: waiting-for-answer, cannot-reproduce
